README.md
To avoid confusion for those who visit GitHub repo.
=> Remove Maven/Gradle/Ivy reference until release is completed.

.travis.yml, README.md, acceptance-tests/pom.xml, eclipse-collections-api/pom.xml, eclipse-collections-code-generator-ant/pom.xml, eclipse-collections-code-generator-maven-plugin/pom.xml, eclipse-collections-code-generator/pom.xml, eclipse-collections-forkjoin/pom.xml, eclipse-collections-testutils/pom.xml, eclipse-collections/pom.xml, jmh-scala-tests/pom.xml, jmh-tests/pom.xml, junit-trait-runner/pom.xml, performance-tests/pom.xml, pom.xml, serialization-tests/pom.xml, unit-tests-java8/pom.xml, unit-tests/pom.xml
* Add Travis badge to README.
* Rearrange the final two sections of the README so that the links are gathered at the end.
* Sort the travis builds by the typical amount of time they take to run, descending. If they are kicked off in order, they'll be more likely to finish around the same time.
* Configure a Travis job that uses Java 7 for the modules that are backwards compatible.
* Remove unused maven plugin.
* Configure all modules to use the parent pom.xml.
* Configure maven-compiler-plugin through properties.
=> Several improvements to the build.

eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/UnifiedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/strategy/mutable/UnifiedSetWithHashingStrategy.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/UnifiedMapTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/AbstractMutableSetTestCase.java
Corresponding to the 2 changes below.
https://github.com/goldmansachs/gs-collections/commit/4fd18e9121dfbbc2eb53ada8ded73bba25269ad7
https://github.com/goldmansachs/gs-collections/commit/bd31d1c74a032ee1c1f11eb5f9a5fd80f5bfad24
=> Fix UnifiedSet$ChainedBucket.removeLongChain() method.

CONTRIBUTING.md, README.md
It would be easier to browse the markdown from my repo.
https://github.com/itohro/eclipse-collections/blob/master/README.md
https://github.com/itohro/eclipse-collections/blob/master/CONTRIBUTING.md
The changes assumes the links to Wiki below exists in original repo. Please also have a look at Wiki links below. I've added you as a collaborator to my repo, so feel free to edit these Wiki pages if you find necessary. Once they look good, I'll put them into eclipse/eclipse-collections Wiki.
https://github.com/itohro/eclipse-collections/wiki (we can enrich this page later)
https://github.com/itohro/eclipse-collections/wiki/Eclipse-Collections-Developers-Guide
https://github.com/itohro/eclipse-collections/wiki/Roadmap
=> Add community references to README.md and CONTRIBUTING.md.

README.md
PME should have been PMI (Project Management Infrastructure).
=> Fix typo for Project Management Infrastructure.

.gitignore
This is added so that Hudson maven build can commit updated pom files as part of release build, without committing local maven repository under the workspace.
FYI attaching POC release build console: https://hudson.eclipse.org/collections/job/eclipse-collections-release/5/consoleFull
=> Add .maven folder to .gitignore file.

CONTRIBUTING.md
The ip-validation by Eclipse requires all commits to be signed-off. This pull request add the instructions to sign-off the commits.
=> Add instructions for commit sign-off to contribution guide.

eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/AbstractBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableSingletonBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/UnifiedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/strategy/mutable/UnifiedMapWithHashingStrategy.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/ArrayStack.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/UnifiedMapTestCase.java
- Simplify and optimize a few methods in ImmutableSingletonBag.
- Fix performance problem in ArrayStack.minBy().
- Optimize UnifiedMap.getFirst() to not delegate to an iterator.
- Optimize AbstractBag for all MutableBagIterable targets, not just MutableBag targets.
=> Simplify and optimize a few methods.

unit-tests/src/test/java/org/eclipse/collections/impl/utility/IterateTest.java
While working on Iterate.toMultimap(), there was an unused variable warning in the test. The test was present to test for inter-op with ArrayList. The ArrayList was never used.
This change is to use the already existing ArrayList and test for inter-op.
=> Fix unit test of Iterate.chunk() to test inter-op with JDK Collections.

eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/RandomAccessListIterate.java
Extracted size variables to make iteration patterns in RandomAccessListIterate consistent.
=> Extract size variables.

eclipse-collections/src/main/java/org/eclipse/collections/impl/block/procedure/MultimapKeyValuePutAllProcedure.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/Iterate.java, serialization-tests/src/test/java/org/eclipse/collections/impl/block/procedure/MultimapKeyValuePutAllProcedureSerializationTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/IterateTest.java
Adding `toMultimap()` on `RichIterable` is a major version change. It can be added in the static utility for a minor version.
There is a new [MultimapKeyValuePutProcedure](https://github.com/nikhilnanivadekar/eclipse-collections/blob/bc7c316629762b43d5d8b05e9a1e5956d7557501/eclipse-collections/src/main/java/org/eclipse/collections/impl/block/procedure/MultimapKeyValuePutProcedure.java) created, if this will be a major version change, I can inline the call for minor version change, and replace with the `Procedure` in major version.
I have only added the `targetMultimap` variant of `toMultimap()`, this is because I want users to control the output instead of deciding which type of `Multimap` is returned for a particular `Iterable`.
=> Implement Iterate.toMultimap()

junit-trait-runner/pom.xml
Alternatively, we could set maven.deploy.skip to true for these two modules.
=> Add release-artifacts profile to the build in the junit-trait-runner maven module.

junit-trait-runner/pom.xml
Another try at getting the build to pass. I suspect that deployment to maven central is failing on this one module due to a mismatch between the groupId and the package name. At this point, I'd rather work on the fix on master, and get the 7.0.x branch deployed without this new, optional module.
=> Skip deployment of the junit-trait-runner maven module.

eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/ArrayIterate.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/ArrayIterateTest.java
With the bug, splitting `{1, 2, 3, 4, 5, 6, 7}` into chunks of size 2 was giving `[[1, 2], [1, 2], [1, 2], [1]]`.
=> Fix bug in ArrayIterate.chunk().

.travis.yml, acceptance-tests/pom.xml, acceptance-tests/src/test/java/org/eclipse/collections/impl/map/mutable/ParallelMapIteratePutAcceptanceTest.java, acceptance-tests/src/test/java/org/eclipse/collections/impl/map/mutable/ParallelUnsafeMapIteratePutAcceptanceTest.java, pom.xml
* Add periodic logging to the parallel map acceptance tests to prevent timeouts.
* Set up a Travis job to compile, but not run, jmh-tests and performance-tests.
* This replaces the build which compiled all modules with a much faster one that compiles the ones not included in other jobs.
* Move the slowest Travis job to run first.
=> Improve the Travis builds.

pom.xml
forkMode has been deprecated since surefire version 2.14 and been
replaced with forkCount and reuseForks.
Signed-off-by: Philippe Marschall <philippe.marschall@gmail.com>
=> Replace forkMode with forkCount

eclipse-collections/src/main/java/org/eclipse/collections/impl/block/procedure/MultimapKeyValuePutProcedure.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/Iterate.java, serialization-tests/src/test/java/org/eclipse/collections/impl/block/procedure/MultimapKeyValuePutProcedureSerializationTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/IterateTest.java
Iteration pattern similar to `Iterate.toMultimap()` where both keys and values need to be transformed.
=> Implement Iterate.groupByAndCollect().

eclipse-collections-code-generator-maven-plugin/src/main/java/org/eclipse/collections/codegenerator/maven/GenerateMojo.java
The GenerateMojo uses the deprecated expression syntax which results in
deprecation warnings during the build.
Switch to the property or default value syntax that is recommended by
Maven.
Signed-off-by: Philippe Marschall <philippe.marschall@gmail.com>
=> Fix GenerateMojo Deprecated Syntax Warnings

RELEASE_NOTE_DRAFT.md, eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/MutableBagIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/AbstractHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/SynchronizedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/UnmodifiableBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/SynchronizedSortedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/TreeBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/UnmodifiableSortedBag.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/bag/mutable/sorted/MutableBagIterableTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/bag/mutable/sorted/MutableSortedBagNoComparatorTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/bag/mutable/sorted/MutableSortedBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBagAsWriteUntouchableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MutableBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/SynchronizedBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/sorted/mutable/AbstractMutableSortedBagTestCase.java
=> Change MutableBagIterable.addOccurrences(T item, int occurrences) to return the updated number of occurrences instead of void.

RELEASE_NOTE_DRAFT.md, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/MutableMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/AbstractMutableMultimap.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/AbstractMutableMultimapTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/set/AbstractMutableSetMultimapTestCase.java
=> Implement MutableMultimap.putAllPairs(Iterable<Pair<K, V>> keyValuePairs).

RELEASE_NOTE_DRAFT.md, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/AbstractMutableList.java
Current implementation of `MutableList.chunk()` uses an iterator. Optimize to use the backing array when the list is RandomAccess. 
Currently all implementations which extend `AbstractMutableList` are RandomAccess.
=> Optimize MutableList.chunk() for RandomAccess lists

RELEASE_NOTE_DRAFT.md, eclipse-collections-api/src/main/java/org/eclipse/collections/api/LazyIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/block/predicate/DropWhileIterablePredicate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/AbstractLazyIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/DropIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/DropWhileIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/LazyIterableAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/TakeWhileIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/iterator/DropIterator.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/iterator/TakeWhileIterator.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/Interval.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/LazyIterate.java, serialization-tests/src/test/java/org/eclipse/collections/impl/block/predicate/DropWhileIterablePredicateSerializationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/lazy/primitive/LazyIterableTestHelper.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/lazy/DropIterableNoIteratorTest.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/lazy/DropWhileIterableNoIteratorTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/AbstractLazyIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/DropWhileIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/TakeWhileIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/iterator/DropIteratorTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/iterator/TakeWhileIteratorTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/IntervalTest.java
1) Implement LazyIterable.takeWhile(Predicate) and LazyIterable.dropWhile(Predicate).
2) Bug fix for Interval.take(0).
3) Fix warnings for Javadoc in LazyIterate where period was missing.
=> Implement LazyIterable.takeWhile(Predicate) and LazyIterable.dropWhile(Predicate).

CONTRIBUTING.md, pom.xml
Reflect couple of feedback from contributors.
- It is reported that build fails with maven 3.0.x. Explicitly mention minimum working version 3.1.0.
- It is reported that findbugs build fails following the instruction. Made it sync with Travis CI findbugs build option.
=> Enforce maven version to 3.1.0+ and add supplimentary information to CONTRIBUTING.md.

RELEASE_NOTE_DRAFT.md, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/primitiveArrayListTest.stg
As suggested by @motlin in the link below.
https://github.com/eclipse/eclipse-collections/pull/105
Add more tests for <primitive>ArrayList.newWithNValues.
Signed-off-by: guoci <zguoci@gmail.com>
=> In <primitive>ArrayList.newWithNValues, replace loop with Arrays.fill

eclipse-collections-api/src/main/java/org/eclipse/collections/api/block/SerializableComparator.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/block/function/Function.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/block/function/Function0.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/block/function/Function2.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/block/function/Function3.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/block/predicate/Predicate.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/block/predicate/Predicate2.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/block/procedure/ObjectIntProcedure.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/block/procedure/Procedure.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/block/procedure/Procedure2.java, eclipse-collections-code-generator/src/main/java/org/eclipse/collections/codegenerator/model/Primitive.java, eclipse-collections-code-generator/src/main/resources/api/block/predicate/primitivePredicate.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/block/predicate/MapEntryPredicate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/block/predicate/PairPredicate.java, findbugs-exclude.xml, unit-tests/src/test/java/org/eclipse/collections/impl/map/fixed/EmptyMapTest.java
The first commit changes the Object functional interfaces like Procedure to extend the JDK functional interfaces like Consumer.
The second commit handles primitive predicates. The work is not complete until we do all primitive functional interfaces but I'm hoping to get help with that effort.
=> Change our functional interfaces to extend the JDK functional interfaces.

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/Iterate.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/IterateTest.java
- chunk, zip, zipWithIndex, sumBy{Int, Long, Float, Double}
- select{With}, reject{With}, collect{With}, partition{With}
- collect{Boolean, Byte, Char, Short, Int, Long, Float, Double}
- add reduceInPlace methods to Iterate and remove unnecessary Procedures.cast() calls
=> Add Collector implementations to Collectors2 for additional API methods available on RichIterable

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/immutable/AbstractImmutableList.java, unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java
Improve speed of AbstractImmutableList.chunk() by using sublists [Fixes #116]. AbstractMutableList.chunk() still needs to be discussed as mentioned in pull request #118.
=> Improve speed of AbstractImmutableList.chunk() by using sublists

junit-trait-runner/pom.xml
Enabling junit-trait-runner deployment again for 8.0.0 release.
I suspect the [deployment error we saw earlier](https://hudson.eclipse.org/collections/job/deploy/12/console) (Connection Reset) was related to the issues below. I hope the workaround (turn off clean workspace option) would work. Let's try and see how it goes. 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=497132
https://bugs.eclipse.org/bugs/show_bug.cgi?id=492412
=> Deploy junit-trait-runner module.

junit-trait-runner/pom.xml
In Hudson build, junit-trait-runner deployment failed with "Connection reset" error that's similar to these bugs ([494371](https://bugs.eclipse.org/bugs/show_bug.cgi?format=multiple&id=494371) and [492421](https://bugs.eclipse.org/bugs/show_bug.cgi?id=492412)). Need to file Eclipse/Hudson bug to track the issue. 
https://hudson.eclipse.org/collections/job/deploy/17/console
In the meantime we disable the deployment of junit-trait-runner.
=> Disable junit-trait-runner module deployment.

CONTRIBUTING.md
Eclipse Foundation now has ECA (Eclipse Contributor Agreement) instead of CLA (Contributor License Agreement).
Updated CONTRIBUTING.md accordingly.
CLA: https://eclipse.org/legal/CLA.php
ECA: https://www.eclipse.org/legal/ECA.php
=> Update Contributor License information with latest ECA.

eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/FastList.java
Fixes goldmansachs/gs-collections#33
Signed-off-by: Christopher Clark <csquared@cs.washington.edu>
=> Optimize List.clear methods to avoid clearing unused memory

pom.xml
Once this is merged, I'll create a branch `7.1.0` and `8.0.0` and cherry pick this commit to those branches, move each tag to the new commit and re-generate Javadoc.
=> Remove JMH tests and generator codes from Javadoc output. Closes #150.

pom.xml
Re-submitting as mentioned in #158 .
=> [Re-submit] Cherry pick Javadoc fixes to 8.0.x branch.

pom.xml
Ive been experimenting this with a [branch](https://github.com/eclipse/eclipse-collections/tree/signjar) in eclipse repo and all build issues have been sorted out by now.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=510109
https://bugs.eclipse.org/bugs/show_bug.cgi?id=512691
After this is merged, I'll get rid of `signjar` branch and `signjar-expr` tag in eclipse repo.
=> Add jarsign step as part of deploy build. Closes #152.

pom.xml
Removal of `sonar.language` allows to get rid of warnings such as
```
[WARNING] File '...' is ignored because it doens't belong to the forced langauge 'java'
```
Other (`sonar.dynamicAnalysis`, `sonar.core.codeCoveragePlugin`, `sonar.clover.version`) have no effect.
=> Remove useless declaration of properties for SonarQube

pom.xml
First step regarding Java 9 - is to execute tests with it.
In absence of usage of [Maven Toolchains](https://maven.apache.org/guides/mini/guide-using-toolchains.html), build should itself be executed with JDK 9 EA because `maven-surefire-plugin` uses JDK that was used for Maven execution. But  currently it fails - see
* [log prior to upgrade of `maven-jar-plugin`](https://github.com/eclipse/eclipse-collections/files/870527/log1.txt)
* [log after upgrade of `maven-jar-plugin`, but prior to upgrade of `maven-source-plugin`](https://github.com/eclipse/eclipse-collections/files/870529/log2.txt)
After upgrade of both there are still problems with JDK 9 EA - compilation errors:
* [in module `eclipse-collections`](https://github.com/eclipse/eclipse-collections/files/870530/log3.txt)
* and even …
=> Yak shaving: upgrade maven-jar-plugin and maven-source-plugin

.travis.yml
SonarQube analysis is executed for the each of 5 jobs - see https://travis-ci.org/eclipse/eclipse-collections/jobs/215394107 and https://travis-ci.org/eclipse/eclipse-collections/jobs/215394108 for example, whereas should be executed only for job that has `DESC` `unit tests`. Because of this generation of 5 reports approximately at the same time, server side processing fails for 4 out of 5 of those reports:
This change fixes condition, so that only one job will be doing analysis.
=> Fix condition that triggers SonarQube analysis

eclipse-collections-code-generator/src/main/resources/impl/bag/immutable/immutablePrimitiveHashBag.stg, eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutableObjectPrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutablePrimitiveObjectHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutablePrimitivePrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/primitiveHashSet.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableEmptyBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableSingletonBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/immutable/AbstractImmutableBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/immutable/AbstractImmutableCollection.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/parallel/AbstractParallelIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/strategy/mutable/UnifiedSetWithHashingStrategy.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableArrayStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/ArrayStack.java
These compilation errors were revealed during attempt to use JDK 9 EA b162 for build of project - see https://github.com/eclipse/eclipse-collections/pull/234#issue-217022672
All they originate from the code that uses same pattern:
```java
class Pattern {
interface MutableObjectByteMap {
<V> MutableCollection<V> collect(ByteToObjectFunction<? extends V> function);
}
interface MutableCollection<T> {
ImmutableCollection<T> toImmutable();
}
interface ImmutableCollection<T> { }
interface ByteToObjectFunction<T> { }
MutableObjectByteMap delegate;
<V> ImmutableCollection<V> example(ByteToObjectFunction<? extends V> function) {
return delegate.collect(function).toImmutable();
}
}
```
Compilation of this `Pattern.java` with JDK 8u121 and OpenJDK 9b52 succeeds, but fails with OpenJDK 9b53:
``` …
```
=> Fix compilation errors

eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Multimaps.java
=> Deprecate EMPTY Multimap instances in org.eclipse.collections.impl.factory.Multimaps.

eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/Verify.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/block/factory/Functions.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/block/factory/Predicates.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/block/factory/Procedures.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/parallel/set/ParallelCollectIterable.java, unit-tests/src/test/java/org/eclipse/collections/impl/AnagramTest.java
I think these are last of the compilation issues with JDK-9-EA-163.
Few notes:
`Functions`, `Predicates`, `Procedures`, `Verify`: Diamond operator is not able to infer the type arguments, so mentioning the types explicitly fixes the compilation problem.
=> Fix compilation issues.

.travis.yml, p2-repository/README.md, p2-repository/org.eclipse.collections/.project, p2-repository/org.eclipse.collections/osgi.bnd, p2-repository/org.eclipse.collections/pom.xml, p2-repository/org.eclipse.collections/src/main/resources/OSGI-INF/l10n/bundle.properties, p2-repository/org.eclipse.collections/src/main/resources/about.html, p2-repository/pom.xml, pom.xml
This adds the initial recipe for generating an OSGi bundle for Eclipse Collections. The bundle is a combination of the main library and the api. It runs as part of the main build an produces a p2 repo with what is available in the Maven reactor.
#223 
/cc @kthoms @nikhilnanivadekar
=> [#223] Create a  p2 repository (based on EBR)

eclipse-collections/src/main/java/org/eclipse/collections/impl/set/sorted/immutable/ImmutableTreeSet.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/SortedSetsTest.java
These two fixes will optimize the construction of ImmutableTreeSet.
A note regarding optimizing constructor with array as an input parameter, there are 3 copies of array created. This will lead to excess garbage, but I do not know how I can avoid that. I am open to feedback. Below are the JMH Test results, where you can observe that we will improve performance by a great degree.
JMH Tests:
Version|Benchmark|Mode|Cnt|Score|Sign|Error|Units
-------|---------|-----|---|-----|----|-----|--------------
Old|array1Dups|thrpt|40|48,196.78|±|3130.292|ops/s|
New|array1Dups|thrpt|40|48,631.08|±|4602.933|ops/s|
Old|array1Dups_Reversed|thrpt|40|44,815.05|±|4799.93|ops/s|
New|array1Dups_Reversed|thrpt|40|48,380.77|±|4943.369|ops/s|
Old|array1NoDups|thrpt|40|44,204.53|±|3108.543|ops/s| …
=> Optimize constructors of ImmutableTreeSet.

eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/Verify.java, eclipse-collections-testutils/src/test/java/org/eclipse/collections/impl/test/VerifyTest.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/SerializableDoubleSummaryStatistics.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/SerializableIntSummaryStatistics.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/SerializableLongSummaryStatistics.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/ArrayListIterate.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableDoubleSummaryStatisticsSeralizationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableIntSummaryStatisticsSeralizationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableLongSummaryStatisticsSeralizationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/SummaryStatisticsSeralizationTest.java
1) Deprecate Verify#assertShallowClone()
2) Add Assume keyword for Serialization tests where reflection is used
3) Set fields as null in the ignored exception block: This is required as the exception is thrown at setAccessible(true). However, the field is not null, due to which Java 9 regression build fails due to IllegalAccessError (reflection for Java 9)
=> More fixes for Java 9 compatibility

eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/CompositeIterable.java
Get LazyIterableAdapter::concatenate and LazyIterate::composite to return a
new, specialized version of CompositeIterable, which implements a size
method whose complexity is O(k), where k is the number of concatenated rich
iterables, instead of O(n), where n is the total number of elements in the
concatenation.
See issue #279
Signed-off-by: Olivier Cinquin <olivier.cinquin@uci.edu>
=> Improve efficiency of size method for concatenated rich iterables

.travis-command-jdk9.sh, .travis.yml, eclipse-collections-api/pom.xml, eclipse-collections-forkjoin/pom.xml, eclipse-collections-testutils/pom.xml, eclipse-collections/pom.xml, pom.xml
1) Remove Apache Felix plugin:
Removal of Apache Felix plugin will result in OSGi bundles not exported under eclipse-collections, eclipse-collections-api. However, these bundles are exported in p2 repository. Users should start using the same.
This will reflect in the release notes.
This is a compatibility breaking change.
2) Java 9 Regression builds
=> Remove Apache Felix plugin, Add Java 9 regression build

eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/ImmutableList.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/ListIterable.java, eclipse-collections-code-generator/src/main/resources/api/list/primitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/AbstractBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/strategy/immutable/ImmutableEntryWithHashingStrategy.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/tuple/ImmutableEntry.java
=> Add covariant override for subList() in ListIterable hierarchy, fix Javadoc warnings.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/InternalIterable.java, unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java
This implementation takes a Consumer as argument instead of a Procedure.
This avoids calls to forEach falling back on the Java 8 Iterable default
implementation, which instantiates an iterator.
Note that, because this is a default interface implementation, the API
is effectively unchanged.
This partially addresses issue #147.
Signed-off-by: Olivier Cinquin <olivier.cinquin@uci.edu>
=> Add an efficient default implementation of forEach.

p2-feature/.project, p2-feature/.settings/org.eclipse.core.resources.prefs, p2-feature/org.eclipse.collections.feature/.project, p2-feature/org.eclipse.collections.feature/build.properties, p2-feature/org.eclipse.collections.feature/epl-v10.html, p2-feature/org.eclipse.collections.feature/feature.xml, p2-feature/org.eclipse.collections.feature/license.html, p2-feature/org.eclipse.collections.feature/pom.xml, p2-feature/org.eclipse.collections.repository/.project, p2-feature/org.eclipse.collections.repository/category.xml, p2-feature/org.eclipse.collections.repository/pom.xml, p2-feature/pom.xml
As discussed in #288 Eclipse Collections does not provide an Eclipse Feature, used to provide end-user visible display in the Simultaneous Release repository.
The EBR based repository generation does not seem to provide any way to inject a feature generation, so the only way I could see was to provide another maven configuration that relies on the previously created repository to provide a new one with a corresponding feature project.
This configuration can be started by executing `mvn clean install` from the new folder `p2-repository/feature-repository` folder, but only after the original build executed successfully. After the new tasks execute the created repository will be available from `p2-repository/feature-repository/org.eclipse.collections.repository/target/repository` folder.
=> Provide a feature project for release train

docs/guide.md
Invalid argument order: [Collectors#joining(CharSequence delimiter, CharSequence prefix, CharSequence suffix)](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#joining-java.lang.CharSequence-java.lang.CharSequence-java.lang.CharSequence-)
=> Fix Java 8 Collectors#joining(String, String, String) usage

p2-feature/pom.xml
The PR #383 introduced a separate build to provide Eclipse features to the Photon Simultaneous Release repository; however, it incorrectly referenced the original parent instead of being entirely standalone.
This change fixes the issue by removing the parent declaration from the p2-feature module.
=> Fixing feature build

eclipse-collections-code-generator/src/main/resources/copyrightAndOthers.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableArrayBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/AbstractMutableBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/immutable/AbstractImmutableSortedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/AbstractMutableSortedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/immutable/AbstractImmutableBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/mutable/AbstractMutableBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/immutable/AbstractImmutableList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/AbstractUnifiedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/immutable/AbstractImmutableSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/SetAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/sorted/immutable/AbstractImmutableSortedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/sorted/mutable/SortedSetAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/sorted/mutable/TreeSortedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/ArrayListIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/ListIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/RandomAccessListIterate.java
=> optimize zip() by pre-sizing target. Fixes #376

RELEASE_NOTE_DRAFT.md, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/UnifiedMap.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/mutable/UnifiedMapNoIteratorTest.java
=> Optimize UnifiedMap#detectOptional(Predicate2) to not use an iterator. Closes #442.

unit-tests-java8/src/test/java/org/eclipse/collections/test/map/mutable/UnifiedMapWithHashingStrategyNoIteratorTest.java
I find several methods in UnifiedMapWithHashingStrategy could be optimized, so I added UnifiedMapWithHashingStrategyNoIteratorTest in prep for that work. 
I also found a missing null check bug in `index(K key)` and fixed it, too.
=> Add UnifiedMapWithHashingStrategyNoIteratorTest.

eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/UnifiedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/strategy/mutable/UnifiedSetWithHashingStrategy.java
Avoids casting Objects to T that may be either T or the null sentinel.
=> Fix invalid cast in UnifiedSet.trimToSize().

.travis-command-ea-builds.sh, .travis.yml, pom.xml
Once Java-10 is released and has a GA build, we will replace Java-9 build with Java-10.
Please note JaCoCo execution is skipped in both the EA builds. Refer to JaCoCo issue: https://github.com/jacoco/jacoco/issues/629
=> Add Regression builds for Java-10, Java-11, upgrade JaCoCo to 0.8.0

eclipse-collections-testutils/src/test/java/org/eclipse/collections/impl/test/VerifyTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableDoubleSummaryStatisticsSeralizationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableIntSummaryStatisticsSeralizationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableLongSummaryStatisticsSeralizationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/SummaryStatisticsSeralizationTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableDoubleSummaryStatisticsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableIntSummaryStatisticsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableLongSummaryStatisticsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/SummaryStatisticsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/ListsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/SetsTest.java
This check was added when reflection was banned by default in Java-9. But since it is only a warning currently, we don't need this check.
=> Remove Java-8 check from tests.

eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/UnifiedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/strategy/mutable/UnifiedMapWithHashingStrategy.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/AbstractUnifiedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/UnifiedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/strategy/mutable/UnifiedSetWithHashingStrategy.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/UnifiedMapOverridesTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/strategy/mutable/UnifiedMapWithHashingStrategyOverridesTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/UnifiedSetOverridesTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/UnifiedSetWithHashingStrategyOverridesTest.java
Unit tests rely on Map/Set being able to clone or create empty copies of themselves. Most changes to code are due to that.
=> Allow index() to be overridden in sets and maps.

eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/AbstractImmutableBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/AbstractMutableBagIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/immutable/AbstractImmutableSortedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/AbstractSynchronizedRichIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/AbstractLazyIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/parallel/AbstractParallelIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/FastList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/immutable/AbstractImmutableMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/AbstractMutableMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/AbstractMutableMapIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/immutable/AbstractImmutableSortedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/mutable/AbstractMutableSortedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/AbstractUnifiedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableArrayStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/ArrayStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/RandomAccessListIterate.java
Signed-off-by: Lorenzo Addazi <lorenzo.addazi@tutanota.com>
=> Optimize implementations of groupByUniqueKey() by pre-sizing the target maps. #445

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/FastList.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/FastListTest.java
This is for issue https://github.com/eclipse/eclipse-collections/issues/365 
Signed-off-by: sone tsuyoshi <Tsuyoshi.Sone@gs.com>
=> Add check on FastList for initialCapacity < 0 #365

serialization-tests/src/test/java/org/eclipse/collections/impl/block/procedure/primitive/CollectBooleanProcedureSerializationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/block/procedure/primitive/CollectByteProcedureSerializationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/block/procedure/primitive/CollectCharProcedureSerializationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/block/procedure/primitive/CollectDoubleProcedureSerializationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/block/procedure/primitive/CollectIntProcedureSerializationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/block/procedure/primitive/CollectLongProcedureSerializationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/block/procedure/primitive/CollectShortProcedureSerializationTest.java
Adding Serialization Test for CollectPrimitiveProcedure as discussed in https://github.com/eclipse/eclipse-collections/pull/531
Signed-off-by: sone tsuyoshi <Tsuyoshi.Sone@gs.com>
=> Add Serialization Tests for CollectPrimitiveProcedure

eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/map/MutableMapFactory.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/MutableMapFactoryImpl.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/MapsTest.java
For ImmutableMapFactory, we already have ofAll() and withAll(). But ofMap() and ofMapIterable() are verbose, intuitive and unambiguous.
=> Implement a Map factory method that takes a Map parameter. Fixes #457.

.mvn/maven.config, .travis-command-ea-builds.sh, .travis.yml
This change makes it so that the flags --show-version and --errors are always on, so you don't need to specify them on the command line.
=> Add .mvn/maven.config with options --show-version and --errors.

pom.xml
This makes it so that if you invoke `mvn` without any goals, it will default to `mvn clean install checkstyle:check`
=> Add maven default goals.

.idea/compiler.xml, .idea/libraries/Maven__com_google_code_findbugs_jsr305_3_0_2.xml, .idea/libraries/Maven__com_google_errorprone_error_prone_annotations_2_1_3.xml, .idea/libraries/Maven__com_google_j2objc_j2objc_annotations_1_1.xml, .idea/libraries/Maven__org_checkerframework_checker_qual_2_0_0.xml, .idea/libraries/Maven__org_codehaus_mojo_animal_sniffer_annotations_1_14.xml, .idea/scala_compiler.xml, acceptance-tests/acceptance-tests.iml, eclipse-collections-forkjoin/eclipse-collections-forkjoin.iml, eclipse-collections-testutils/eclipse-collections-testutils.iml, eclipse-collections-testutils/pom.xml, jmh-scala-tests/jmh-scala-tests.iml, jmh-tests/jmh-tests.iml, jmh-tests/pom.xml, performance-tests/performance-tests.iml, pom.xml, scala-unit-tests/scala-unit-tests.iml, serialization-tests/serialization-tests.iml, unit-tests-java8/unit-tests-java8.iml, unit-tests/unit-tests.iml
- Upgrade JMH from 1.19 to 1.21.
- Upgrade HPPC from 0.7.2 to 0.8.1.
- Upgrade Guava from 21.0 to 25.1-jre.
- Upgrade Scala from 2.11.7 to 2.12.6.
- Upgrade version of commons-codec from 1.10 to 1.11.
=> Upgrade versions of library dependencies.

.travis-command-ea-builds.sh, .travis.yml, pom.xml
=> Enable Java-12 EA build, allow EA build failures, upgrade JaCoCo to 0.8.2 to fix Java 11,12 build failures. Fixes #605

eclipse-collections/src/main/java/org/eclipse/collections/impl/map/immutable/ImmutableDoubletonMap.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/immutable/ImmutableUnifiedMapTest.java
Closes #443 
(P.s. a minor start 🙂 )
cc: r? @nikhilnanivadekar
=> fix(MapIterable): flipUniqueValues to throw error when it has duplicates

eclipse-collections-code-generator/src/main/resources/api/block/function/primitivePrimitiveToPrimitiveFunction1.stg, eclipse-collections-code-generator/src/main/resources/api/primitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/impl/collection/mutable/abstractSynchronizedPrimitiveCollection.stg, eclipse-collections-code-generator/src/main/resources/impl/collection/mutable/abstractUnmodifiablePrimitiveCollection.stg, eclipse-collections-code-generator/src/main/resources/impl/synchronizedPrimitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/primitiveLiteral.stg, eclipse-collections-code-generator/src/main/resources/test/collection/mutable/abstractPrimitiveIterableTestCase.stg, unit-tests/src/test/java/org/eclipse/collections/impl/collection/mutable/primitive/AbstractBooleanIterableTestCase.java
Hi,
This is a PR for #312, this is not finished, but I'm making this PR public in order to get feedbacks as soon as possible.
TODO:
I think that after that, this can be merged and then we could open the following new issues:
- add optimized implementation of `reduce` and `reduceInPlace` in the right places
- other ideas?
Open questions:
- I feel like using a default method (as recommended, see https://github.com/eclipse/eclipse-collections/issues/312#issuecomment-438015186) is dangerous because you never know when it is needed to override or not the method. For example I almost missed abstract synchronized and unmodifiable primitive collections. I'm still not sure if I missed other implementations… If I had added the implementation in the abstract class, I would have a clearer view of the …
=> reduce for primitive iterables

eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Sets.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/LazyIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/SetIterables.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/LazyIterateTest.java
This generalize the already available `Sets.cartesianProduct` and `SetIterables.cartesianProduct` to any `Iterable`.
This is something I did need many times and I was bothered to have to convert my two `LazyIterable`s into concrete `Set`s just to get the product of their elements.
=> Implement LazyIterate.cartesianProduct

.gitignore, .idea/compiler.xml, .idea/encodings.xml, .idea/scala_compiler.xml, acceptance-tests/acceptance-tests.iml, eclipse-collections-forkjoin/eclipse-collections-forkjoin.iml, eclipse-collections-testutils/eclipse-collections-testutils.iml, jmh-tests/jmh-tests.iml, performance-tests/performance-tests.iml, scala-unit-tests/scala-unit-tests.iml, serialization-tests/serialization-tests.iml, unit-tests-java8/unit-tests-java8.iml, unit-tests/unit-tests.iml
Looked at #581 again after @mohrezaei's comment.
The removal of commons-codec affects *.iml files intentionally. The other xml files aren't supposed to be changed, which is frustrating / confusing. In this commit I'm syncing up the iml files which should exactly match across all our computers. I'm also syncing the other xml files in the hope that they match, or at least match more closely. If there are remaining diffs, I'd like to see them.
Projects that use maven or gradle's auto-import can usually delete modules.xml, compiler.xml, encodings.xml, and *.iml. Since we're using and experimenting with TeamCity Inspections builds, we do require these files for those builds to pass. I did try deleting subsets of the files to see what would happen and it does break the Inspections functionality …
=> Refresh IntelliJ project files to remove commons-codec.

.travis.yml
This must have resulted from merging the changes for additional builds separately from the changes for adding the maven wrapper.
=> Configure travis to run maven using the maven wrapper.

eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/mutable/AbstractMultiReaderMutableCollection.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/MultiReaderUnifiedSet.java, scala-unit-tests/src/test/scala/org/eclipse/collections/impl/list/mutable/MultiReaderFastListScalaTest.scala
=> Reduce duplicate readlock and writelock code in MultiReaderFastList, MultiReaderHashBag and MultiReaderUnifiedSet.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/MultiReaderBag.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/bag/MultiReaderBagFactory.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/list/MultiReaderListFactory.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/set/MultiReaderSetFactory.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/MultiReaderList.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/set/MultiReaderSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderMutableBagFactory.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Bags.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Lists.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Sets.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderMutableListFactory.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/MultiReaderMutableSetFactory.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/MultiReaderUnifiedSet.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/BagsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/ListsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/SetsTest.java
hi please find this PR for #705
=> #705 Add interfaces for MultiReader List/Set/Bag

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/IntInterval.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/IntervalTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/primitive/IntIntervalTest.java
Signed-off-by: Chandra Guntur <chandra.guntur@bnymellon.com>
=> Fixes #762. Fix fromToBy & injectInto issues with same start and end with negative step. Add unit tests to Interval as well, to cover the scenario.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MutableMapIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/mutable/AbstractMutableBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMapUnsafe.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/ConcurrentMutableHashMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/MapAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/ordered/mutable/OrderedMapAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/mutable/SortedMapAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/mutable/TreeSortedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/strategy/mutable/UnifiedMapWithHashingStrategy.java
I created a lot of confusion on:
https://github.com/eclipse/eclipse-collections/pull/665#issuecomment-449521787
https://github.com/eclipse/eclipse-collections/issues/677
and now:
https://github.com/eclipse/eclipse-collections/pull/786
I apologize for the confusion. I think that we should pull up a simple implementation as a default method like I have here. I think we may still want to optimize the implementation on hash tables, but the benefit is less clear.
=> Pull the implementation of MutableMapIterable.removeIf() up as a default method.

eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMapWithHashingStrategy.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveBooleanHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitivePrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/primitiveHashSet.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/primitive/ObjectBooleanHashMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/primitive/ObjectBooleanHashMapWithHashingStrategy.java
This will provide a way to dynamically restrict the growth of the backing arrays. See #787 for reference.
=> Expose the allocateTable method as protected

p2-feature/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
=> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/bag/ImmutableBagFactory.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/bag/MutableBagFactory.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MutableBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/BagsTest.java
=> Add new APIs, `ofOccurrences` and `withOccurrences`, to bag mutable and immutable factories 

eclipse-collections-api/src/main/java/org/eclipse/collections/api/tuple/Triple.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/tuple/Triplet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/tuple/TripleImpl.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/tuple/TripletImpl.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/tuple/Tuples.java, java.header, unit-tests/src/test/java/org/eclipse/collections/impl/tuple/TuplesTest.java
An implementation similar to tuple for 3 elements like in Haskell
I use this sometimes and was not part of this great collections framework.
Other frameworks do have this kind of implementations like apache commons lang3
Tuples with more than 2 elements are also a common datatype in a language like Python, .Net and bunch of functional languages.
=> Implementation for 3-tuple, Triple and Triplet

.github/workflows/maven.yml
Builds on Ubuntu and for the following versions of Java:
- 8
- 11
- 14-EA
- 15-EA
Since it uses the Setup Java action from GitHub, it leverages Azul Zulu builds by default. If needed, it is possible to download (wget) and then use the parameter `jdkFile` to tell Setup Java where to get the JDK.
=> Add GitHub Actions Workflow

CONTRIBUTING.md
This is mainly a recommendation inspired from the blog series of Andres Almiray (https://blogs.oracle.com/author/e475065c-7c0f-4efc-98f4-7d6d0212138d): 
> Friends don't let friends use `mvn clean install`
=> use `mvn verify` instead of `mvninstall` in the contributing guide

.travis.yml
This cleans up some travis build, since we have the GitHub Actions 
Part of #821
=> feat: remove redundant travis builds

eclipse-collections-api/src/main/java/org/eclipse/collections/api/bimap/ImmutableBiMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/bimap/MutableBiMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/collection/ImmutableCollection.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/collection/MutableCollection.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/ImmutableMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MutableMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/primitive/ImmutablePrimitiveObjectMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/primitive/MutablePrimitiveObjectMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/sorted/ImmutableSortedMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/sorted/MutableSortedMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/stack/ImmutableStack.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/stack/MutableStack.java
Based on the conversation here: https://github.com/eclipse/eclipse-collections/pull/865#discussion_r419031392 I decided to try to pull up another method that we found, without removing any implementations. This was partially an experiment to see how fast it can be.
=> Pull up RichIterable.groupByUniqueKey() as default methods.

eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveListFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg
toImmutable() method on primitive lists avoids a redundant array creation. The method invokes the withAll(...) immutable factory method, which now also does the check to see if an optimized collection can be instantiated (moved the logic from toImmutable())
=> toImmutable() method on primitive lists avoids a redundant array creation

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/immutable/ImmutableListFactoryImpl.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/FastListTest.java
The toImmutable() call chain now invokes the ImmutableArrayList factory method that takes an iterable rather than an array
=> toImmutable() method on FastList avoids creating a redundant array copy

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/primitive/BooleanArrayList.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/primitive/AbstractBooleanListTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/primitive/BooleanArrayListTest.java
Made removeIf() on BooleanArrayList follow the same implementation approach as on the other primitive lists and FastList
=> Fixes #793: optimizes removeIf() implementation on BooleanArrayList

eclipse-collections/src/main/java/org/eclipse/collections/impl/block/factory/Comparators.java, serialization-tests/src/test/java/org/eclipse/collections/impl/block/factory/ComparatorsSerializationTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/factory/ComparatorsTest.java
Added two factory methods for byFunction comparators that handle null values. They use null safe comparators from java.util.Comparator and follow a similar naming convention.
=> Closes #890: Implements Null Safe Comparators by Function

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/IntInterval.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/primitive/IntIntervalTest.java
Uses direct formulas for `mean()` and `average()`, e.g. (first + last)/2.0, and `sum()`, e.g. size * ((first + last) / 2.0) to eliminate unnecessary object creation (arrays and iterators) and improve performance.
=> Closes #892: Uses direct formulas to calculate sum(), mean(), and average() on IntInterval

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/Interval.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/IntInterval.java, serialization-tests/src/test/java/org/eclipse/collections/impl/list/IntervalSerializationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/list/primitive/IntIntervalSerializationTest.java
The value of size is calculated once on object instantiation rather than every time `size()` is called. The property `size` is transient to preserve serialization compatibility, thus requiring calculating size in the `readObject()` method as well.
=> Closes #894: Memoizes size() value on IntInterval and Interval

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/IntInterval.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/primitive/IntIntervalTest.java
Closes #895: replaces `...UnsupportedOperationException...` with the implementation that follows the pattern in the `Interval` class
=> Closes #895: Implement subList() on IntInterval

eclipse-collections-code-generator/src/main/resources/api/list/mutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/synchronizedPrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/unmodifiablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/abstractPrimitiveListTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/unmodifiablePrimitiveListTest.stg
Adds `shuffleThis()` method to mutable primitive lists (excluding boolean list).  The method randomly permutes the list in place and returns the same list (this). 
=> Closes #728: Adds shuffle operation to primitive lists

checkstyle-configuration.xml, checkstyle-suppressions.xml, eclipse-collections-code-generator/src/main/resources/api/map/immutableObjectPrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/immutablePrimitiveObjectMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/immutablePrimitivePrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/mutableObjectPrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/mutablePrimitiveObjectMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/mutablePrimitivePrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/mutablePrimitiveValuesMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/objectPrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/primitiveObjectMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/primitivePrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/primitiveValuesMap.stg, eclipse-collections-code-generator/src/test/java/org/eclipse/collections/codegenerator/tools/JavadocUtil.java
I have completed Javadocs on the API's `map` package. I am opening a PR to being the review process now before I (or someone else!) moves on to the other packages (`list`, `set`, `bag`, etc.).  In my view, `map` was the highest priority with methods like `getIfAbsentPutWith` that benefited most from Javadocs. Additionally, I'm envisioning many Javadocs in those packages will be copy-paste from what I have here, so I want to confirm the verbiage is right before doing so.
Some non-Javadoc changes included in this PR (which can be taken out if needed):
- Update checkstyle DTD (now content assist works in Eclipse when editing the configs)
- Remove `\r` checkstyle check. I don't see what benefit it provides (from what I can tell, my commits still have just `\n` even from Windows) while just …
=> (Partially) Closes #351: Javadocs for map APIs

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/LongInterval.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/primitive/LongIntervalTest.java
`LongInterval` supports elements of type 'long' but is otherwise consistent with other primitive lists and is limited to an int size.
=> Closes #723 added LongInterval

eclipse-collections-code-generator/src/main/resources/api/list/mutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/abstractPrimitiveListTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/unmodifiablePrimitiveListTest.stg
Implement `swap(index1, index2)` method for swapping two list elements. Add corresponding tests on mutable primitive list tests and default implementations on the respective primitive list interfaces. 
=> Implement swap() method on mutable primitive lists

eclipse-collections-code-generator/src/main/resources/api/block/function/primitiveComparator.stg, eclipse-collections-code-generator/src/main/resources/api/list/mutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/primitiveSort.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/synchronizedPrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/abstractPrimitiveListTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/unmodifiablePrimitiveListTest.stg
Adds indirect sorting methods to primitive collections, which are in addition to the existing `sortThis()`. Unlike `sortThis()`, which uses natural ordering of the primitives, the new methods take a function to generate sort keys with an optional key comparator,  or they can take a primitive comparator.
=> Closes #908: Support sorting of primitive lists by indirect comparison

eclipse-collections-code-generator/src/main/resources/impl/list/mutable/synchronizedPrimitiveList.stg
Ensures that direct calls to `shuffleThis(Random rnd)` are synchronized
=> Closes #914: Synchronized primitive lists adds override for shuffleThis(Random rnd)

CONTRIBUTING.md, README.md
Comments from #873 are fixed in this.
=> Closes #871: Add links for Github interaction to the wiki page

eclipse-collections/bnd.bnd
=> Make sun.misc an optional Import-Package in OSGi metadata

.github/workflows/checkstyle.yml, .idea/codeStyles/Project.xml, checkstyle-configuration.xml, eclipse-collections-code-generator/src/main/resources/api/list/immutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/list/mutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/list/primitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/ordered/orderedPrimitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/api/ordered/reversiblePrimitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/api/stack/immutablePrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/api/stack/mutablePrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/api/stack/primitiveStack.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/primitiveBooleanHashMapKeysViewTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/unmodifiableObjectPrimitiveMapValuesTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/unmodifiablePrimitiveBooleanMapValuesTest.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/strategy/immutable/ImmutableUnifiedMapWithHashingStrategy.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/parallel/ArrayProcedureFJTaskRunner.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/parallel/ObjectIntProcedureFJTaskRunner.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/parallel/ProcedureFJTaskRunner.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/Iterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/IterableIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/IteratorIterate.java, pom.xml, unit-tests-java8/src/test/java/org/eclipse/collections/test/CollisionsTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/list/ListIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/AbstractListTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/primitive/IntIntervalTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/primitive/LongIntervalTest.java
Our original CheckStyle settings file was derived from CheckStyle's [own configuration](https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml). That file has evolved separately from ours over the years. Also, I've seen rule violations creep in that I thought were already banned. Rather than dig into what happened, I just synced up some rule settings from "upstream" and fixed the violations that I noticed.
=> Fix CheckStyle whitespace settings.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/FixedSizeList.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/MultiReaderList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastList.java
While reviewing #801, I wanted to point out that methods that return `this` need covariant overrides on all sub-interfaces. I wanted to point to sortThis() as an example and was surprised to find that it's missing overrides.
While unlikely to cause problems for users, I believe this is a breaking change and can wait for the next major version.
=> Add covariant overrides for sortThis().

pom.xml
The reason to remove this is because we need to run deploy builds with JDK 8.
=> Remove unsupported Javadoc option

eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableArrayStack.java
Deprecate ImmutableArrayStack. Closes #976
Signed-off-by: John Jabamani <john.jabamani@bnymellon.com>
=> Deprecate ImmutableArrayStack. Closes #976

.github/workflows/mutation.yml
Found a couple of helpful resources such as [this](https://github.community/t/do-not-run-cron-workflows-in-forks/17636) outlining the solution.
=> Disable mutation tests from running on every fork

.github/workflows/coverage.yaml
Similar to what we did with Mutation tests in this [PR](https://github.com/eclipse/eclipse-collections/pull/993).
=> Disable coverage job from running on every fork

eclipse-collections-code-generator/src/main/resources/api/set/immutablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/api/set/mutablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/api/set/primitiveSet.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractImmutablePrimitiveSetTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractPrimitiveSetTestCase.stg, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractBooleanSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractByteSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractImmutableByteHashSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/ImmutableBooleanHashSetTest.java
=> Implement union operation on primitive sets. Partially addresses issue #310.

unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/AtomicCountProcedureTest.java
@donraab 
Hi, Don
Can you please review the pull request for issue #988? 
A few questions: 
(1) I don't see mockito in test project as dependency. I'm asking because my first impression is to mock a Predicate to test AtomicCountPrecedure, and I don't see mockito used anywhere in eclipse collection test cases. 
(2) Is it a standard to add comments for unit test cases in the project?
Thanks!
Hong
=> Issue# 988: Test Coverage for AtomicCountProcedure

unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/BagAddOccurrencesProcedureTest.java
Closes #989 
The BagAddOccurancesProcedure was missing test cases. I added a test case to cover adding occurrences to an existing bag. I also added a test case to cover the factory method.
=> Add test cases for BagAddOccurrencesProcedure

acceptance-tests/src/test/java/org/eclipse/collections/api/IntIterableAcceptanceTest.java, eclipse-collections-code-generator/src/main/resources/api/primitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/impl/abstractPrimitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/test/collection/mutable/abstractPrimitiveIterableTestCase.stg
Signed-off-by: Rinat Gatyatullin <rinattalgatovich.gatyatullin@bnymellon.com>
I moved up containsAll as a default method on primitive iterables. I was going to add containsAny and containsNone as default methods there so this way they are all in the same place.  The build and tests work fine with this change. If there is some reason to not do this, please let me know and I'll move it back to the abstract primitive iterable where it was before.
=> Optimize containsAll on primitive iterables.

findbugs-exclude.xml
Classes themselves were removed as part of this PR https://github.com/eclipse/eclipse-collections/pull/599.
Deleting references to those classes in findbugs-exclude.xml file in this PR.
=> Remove references to deleted classes in findbugs-exclude file.

eclipse-collections-code-generator/src/main/resources/api/block/function/primitiveComparator.stg, eclipse-collections-code-generator/src/main/resources/api/primitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/test/collection/mutable/abstractPrimitiveIterableTestCase.stg
Supports `toSortedListBy` implementations on primitive Itrerables that accept one of the following:
- a primitive comparator
- a primitive to object function that takes the elements of the iterable
- a primitive to object function that takes iterable elements and a comparator applied to the results of the function
These methods convert the collection to a corresponding primitive Mutable List implementation, which is sorted based on the primitive comparator , the natural order of the values returned by the function, or the comparator applied to the results returned by the function respectively.
=> Closes #1044: Adds toSortedList(Comparator) and toSortedListBy(Function) to primitive Iterables

eclipse-collections-code-generator/src/main/resources/impl/set/mutable/primitiveHashSet.stg
Avoid some unnecessary `toArray` calls.
The new constructor taking a primitive iterable is similar to the existing constructor in primitive hash bag.
=> Optimize primitive hash set newSet and withAll

eclipse-collections/src/main/java/org/eclipse/collections/impl/block/factory/HashingStrategies.java
The helper method is not necessary anymore now that EC is java 8+ only.
=> Replace HashingStrategies.longHashCode with java 8 Long.hashCode

eclipse-collections/src/main/java/org/eclipse/collections/impl/tuple/Tuples.java, unit-tests/src/test/java/org/eclipse/collections/impl/tuple/TuplesTest.java
=> Add converters from Pair and Triple to List types.

.github/workflows/earlyaccess-javadoc.yml, .github/workflows/earlyaccess-unit.yml
Signed-off-by: Rinat Gatyatullin <rinattalgatovich.gatyatullin@bnymellon.com>
Changing to use oracle-actions/setup-java based on the conversation on this issue: https://github.com/sormuras/download-jdk/issues/25
=> Switch to oracle-actions to download JDK for EA builds.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/RichIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java
=> Disambiguate and deprecate primitive injectInto methods on RichIterable.

checkstyle-configuration.xml, eclipse-collections-code-generator/src/main/resources/api/factory/map/mutableObjectPrimitiveMapFactory.stg, eclipse-collections-code-generator/src/main/resources/api/factory/map/mutablePrimitiveObjectMapFactory.stg, eclipse-collections-code-generator/src/main/resources/api/list/mutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/primitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections-code-generator/src/main/resources/test/factory/primitiveObjectMutableMapFactoryTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/abstractPrimitiveBooleanMapKeyValuesViewTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/objectPrimitiveHashMapKeySetTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/synchronizedObjectPrimitiveMapKeySetTest.stg, eclipse-collections-code-generator/src/main/resources/test/set/immutable/immutablePrimitiveKeySetTest.stg, eclipse-collections-code-generator/src/main/resources/test/set/immutable/immutablePrimitivePrimitiveMapKeySetTest.stg, eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/ClassComparer.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMap.java, pom.xml, unit-tests/src/test/java/org/eclipse/collections/impl/SpreadFunctionsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/AtomicCountProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/CollectionRemoveProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/tuple/TuplesTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/ArrayIterateTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/IterateTest.java
I was comparing our rule set to [CheckStyle's rules](https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml) that it applies to its own source code. I made three changes.
1.  Upgrade checkstyle-configuration.xml from 1.2 schema to 1.3 schema.
2.  Upgrade CheckStyle from 9.1 to 10.1.
3.  Turn on CheckStyle rule SingleSpaceSeparator and fix violations.
(1) and (2) were to get in sync.
(3) Is the first of several rules I want to turn on.
=> Turn on CheckStyle rule SingleSpaceSeparator and fix violations.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java, unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java
Resolves #1006 
I read your suggestion @donraab, about "fusing `anySatisfy` and `nonSatisfy` with `contains`". But, I couldn't figure out as to how `anySatisfy` and `nonSatisfy` fit into this context. So, I didn't use those methods for implementing these.
=> Implement containsAny, containsNone, containsAnyIterable, containsNoneIterable on RichIterable.

docs/1-Iteration_Patterns.adoc, docs/2-Collection_Containers.adoc, docs/3-Code_Blocks.adoc, docs/4-Testing_Utilities.adoc, docs/5-Quick_Reference.adoc
=> Fix ref guide's broken links and sundry typos

eclipse-collections-code-generator/src/main/resources/impl/bag/immutable/immutablePrimitiveBagFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/impl/bag/immutable/immutablePrimitiveHashBag.stg, eclipse-collections-code-generator/src/main/resources/impl/bag/mutable/mutablePrimitiveBagFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/test/bag/immutable/immutablePrimitiveHashBagTest.stg, unit-tests/src/test/java/org/eclipse/collections/impl/stream/PrimitiveStreamsTest.java
Please review this PR commit by commit starting from the earliest one. I’ve structured commits to be small and self-contained changes.
Every commit has a detailed message that explains why it was done that way. Of course, if you have additional questions I’m more than happy to answer them.
Closes #1372
=> Optimize withAll for primitive bag factories

eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Sets.java
rename the 'list' parameter in org.eclipse.collections.impl.factory.Sets.adapt to 'set'
=> fix : rename parameter

eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/MultiReaderBag.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/MultiReaderList.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/set/MultiReaderSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/MultiReaderUnifiedSet.java
I was code reviewing changes related to multi-reader collections and I noticed that they're missing a bunch of overrides.
These changes are not technically backwards compatible. I don't know if we're planning on a minor release next. Anyway, I wanted to show the changes even if they can't be merged for a while.
=> Add missing overrides in multi-reader interfaces.

eclipse-collections/src/main/java/org/eclipse/collections/impl/map/strategy/mutable/UnifiedMapWithHashingStrategy.java
PR  - would appreciate a review @donraab 
Looks like existing tests already cover this refactoring
=> Optimize any/all/noneSatisfy on UnifiedMapWithHashingStrategy - closes #1342

docs/2-Collection_Containers.adoc
In line 1278 there is an extra 'I', removed it.
Hi @donraab, 
updated a typo in the doc, please verify and approve for merge.
Thank you!
=> Removed a typo in ImmutableSet

eclipse-collections/src/main/java/org/eclipse/collections/impl/block/factory/Comparators.java, serialization-tests/src/test/java/org/eclipse/collections/impl/block/factory/ComparatorsSerializationTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/factory/ComparatorsTest.java
I have a use-case for sorting where I can answer whether one object should come before another object, but I don't have a Comparator. I looked around for a function that convert a BiPredicate to a Comparator and couldn't find one, so here it is. I looked on Comparator, Comparators, and on BiPredicate.
The unit test sorts Instants using the isBefore() method. This is a good example of using a single-arg, non-static method.
```java
ImmutableList<Instant> orderedInstants = Lists.immutable.with(
Instant.parse("2000-01-01T00:00:00Z"),
Instant.parse("2001-01-01T00:00:00Z"),
Instant.parse("2002-01-01T00:00:00Z"),
Instant.parse("2003-01-01T00:00:00Z"));
MutableList<Instant> shuffledInstants = orderedInstants.toList().shuffleThis();
shuffledInstants.sortThis(Comparators.fromPredicate(Instant::isBef …
```
=> Implement Comparators.fromPredicate(), to create a Comparator from a Predicate2 that can answer isBefore.

acceptance-tests/pom.xml, eclipse-collections-api/pom.xml, eclipse-collections-code-generator-maven-plugin/pom.xml, eclipse-collections-code-generator/pom.xml, eclipse-collections-forkjoin/pom.xml, eclipse-collections-testutils/pom.xml, eclipse-collections/pom.xml, jcstress-tests/pom.xml, jmh-tests/pom.xml, performance-tests/pom.xml, pom.xml, scala-unit-tests/pom.xml, serialization-tests/pom.xml, unit-tests-java8/pom.xml, unit-tests/pom.xml
There is no configuration of a server anywhere in the POMs, so this has no functionality unless some external invocation provides a server url via settings.xml or system properties.
=> Remove sonar-maven-plugin - fixes #1466

pom.xml
The Maven plugin versions specified require a higher Maven core version. This can be checked via `mvn versions:display-plugin-updates`.
=> Use correct minimum Maven version

CONTRIBUTING.md
People are used to copying the complete block from the documentation, and then the prompt will lead to syntax errors.
=> remove prompt from documentation code blocks

acceptance-tests/pom.xml, jmh-tests/pom.xml
This is already specified (with the same version) in eclipse-collections/pom.xml, section pluginManagement. m2e even warns about the duplication.
=> remove duplicate maven-dependency-plugin version

.github/workflows/acceptance.yml, .github/workflows/checkstyle.yml, .github/workflows/earlyaccess-javadoc.yml, .github/workflows/earlyaccess-unit.yml, .github/workflows/javadoc.yml, .github/workflows/mutation.yml, .github/workflows/performance.yml, .github/workflows/unit-no-p2.yml, .github/workflows/unit.yml
The maven wrapper is meanwhile an official Maven project and should be used with the maven groupid. Also silence the download transfer progress on all Maven invocations.
=> Upgrade Maven wrapper

eclipse-collections-code-generator/src/main/resources/test/lazy/abstractLazyPrimitiveIterableTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/lazy/collectPrimitiveIterableTest.stg, eclipse-collections-code-generator/src/main/resources/test/lazy/collectPrimitiveToObjectIterableTest.stg, eclipse-collections-code-generator/src/main/resources/test/lazy/flatCollectPrimitiveToObjectIterableTest.stg, eclipse-collections-code-generator/src/main/resources/test/lazy/primitiveSelectIterableTest.stg, eclipse-collections-code-generator/src/main/resources/test/lazy/primitiveTapIterableTest.stg, eclipse-collections-code-generator/src/main/resources/test/lazy/reversePrimitiveIterableTest.stg
=> @Test(expected=X) → assertThrows(X) in lazy tests

eclipse-collections-code-generator/src/main/resources/test/bag/immutable/immutablePrimitiveEmptyBagTest.stg, eclipse-collections-code-generator/src/main/resources/test/bag/mutable/abstractMutablePrimitiveBagTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/bag/mutable/unmodifiablePrimitiveBagTest.stg
=> @Test(expected=X) → assertThrows(X) in bag tests

unit-tests-java8/src/test/java/org/eclipse/collections/test/IterableTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/OrderedIterableTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/bag/mutable/sorted/MutableSortedBagTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/collection/mutable/MultiReaderMutableCollectionTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/list/ListTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/list/mutable/UnmodifiableMutableListTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/set/mutable/HashBiMapKeySetTest.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/set/mutable/UnifiedMapKeySetTest.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/set/sorted/SortedSetIterableTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/stack/StackIterableTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/stack/mutable/UnmodifiableMutableStackTestCase.java
`@Test` does not have the "expected" field in junit-jupiter.  This is a small first step in moving to junit-jupiter.
=> Replace @Test(expected=X) with assertThrows(X) in unit-tests-java8

eclipse-collections-code-generator/src/main/resources/test/stack/immutable/abstractImmutablePrimitiveStackTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/stack/immutable/immutablePrimitiveArrayStackTest.stg, eclipse-collections-code-generator/src/main/resources/test/stack/immutable/immutablePrimitiveEmptyStackTest.stg, eclipse-collections-code-generator/src/main/resources/test/stack/mutable/abstractMutablePrimitiveStackTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/stack/mutable/abstractPrimitiveStackTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/stack/mutable/unmodifiablePrimitiveStackTest.stg
=> @Test(expected=X) → assertThrows(X) in stack tests

eclipse-collections-code-generator/src/main/resources/test/set/immutable/immutablePrimitiveEmptySetTest.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractImmutablePrimitiveSetTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractPrimitiveSetTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/boxedMutableHashSetTest.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/primitiveHashSetTest.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/unmodifiablePrimitiveSetTest.stg
=> @Test(expected=X) → assertThrows(X) in set tests

eclipse-collections-code-generator/src/main/resources/test/list/mutable/abstractPrimitiveListTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/boxedMutableArrayListTest.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/primitiveArrayListTest.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/unmodifiablePrimitiveListTest.stg
=> @Test(expected=X) → assertThrows(X) in mutable List tests

unit-tests-java8/src/test/java/org/eclipse/collections/test/IterableTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/NoIteratorTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/bag/mutable/MultiReaderHashBagTest.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/bag/mutable/UnmodifiableBagIterableTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/bag/mutable/sorted/MutableBagIterableTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/bag/mutable/sorted/MutableSortedBagTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/bag/mutable/sorted/UnmodifiableSortedBagTest.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/collection/mutable/MultiReaderMutableCollectionTestCase.java
The intention is to keep all the same assertions, but reduce lines of code and reduce number of tests. Our tests are so fast that more time is taken by the junit framework to create test and record results than to execute assertions, so reducing the number of tests can speed up our build a bit.
=> Combine tests in unit-tests-java8 that cover the same method contract.

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/Interval.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/IntervalUtils.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/IntInterval.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/LongInterval.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/IntervalTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/primitive/IntIntervalTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/primitive/LongIntervalTest.java
Closes: #1564 
Hi @donraab,
In this PR, I tried to keep the changes as much consistent as possible.
Upon consideration, I think there might be a different way to approach this.
In my opinion we might consider allowing the direction of the interval to be determined by difference of `from - to`.
1. We allow `step` to have different values and sign
1.a. Pro: Not invasive
1.b. Con: The API doesn't look nice. i.e. fromToBy(0, 10, -1)
2. We allow `step` to only be positive
2.a. Pro: This would reflect more a "real life" situation, where having negative steps is not allowed. i.e. a car is moving in some direction with this many km/h. if the car reverses, the direction changes but the speed is still positive.
2.b. Con: Somehow invasive.
=> reverse interval ranges

eclipse-collections-code-generator/src/main/resources/api/map/objectPrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutableObjectPrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutableObjectPrimitiveSingletonMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMapWithHashingStrategy.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/synchronizedObjectPrimitiveMap.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/AbstractHashBag.java, jmh-tests/src/main/java/org/eclipse/collections/impl/jmh/BagEqualsTest.java
I wrote a JMH Benchmark to compare the performance of the equals methods in HashBag, HashMultiset (Guava) and HashMap (Java). I was surprised to find that HashBag equals was slower than HashMap. I added a new method named shortCircuitKeyValue to Object/Primitive Maps and based the equals method in AbstractHashBag on using this method as a manual way of implementing allSatisfyKeyValue. I had originally added any/all/noneSatisfyKeyValue as well, but backed out those additions as a potential later change.
The following are the results of the JMH tests before and after changes.
Original Code
```
Benchmark                      Mode  Cnt      Score      Error   Units
BagEqualsTest.bagEquals       thrpt   20  19770.401 ±  139.757  ops/ms
BagEqualsTest.mapEquals       thrpt   20  23120.905 ± …
```
=> Add allSatisfyKeyValue method to Object/Primitive Maps to optimize HashBag equals method.

pom.xml
We're already running this plugin as part of continuous integration so the usual thing would be to lock down the version. Maven 4.x together with the enforcer plugin will require this, and I'm running maven 4 locally.
=> Specify the version of maven-wrapper-plugin.

eclipse-collections-code-generator/src/main/resources/api/map/primitivePrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/copyrightOf.stg, eclipse-collections-code-generator/src/main/resources/impl/bag/mutable/primitiveHashBag.stg, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutablePrimitivePrimitiveEmptyMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutablePrimitivePrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutablePrimitivePrimitiveSingletonMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitivePrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/synchronizedPrimitivePrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/test/map/abstractPrimitivePrimitiveMapTestCase.stg, jmh-tests/src/main/java/org/eclipse/collections/impl/jmh/IntBagEqualsTest.java
Before changes:
```
Benchmark                    Mode  Cnt      Score     Error   Units
IntBagEqualsTest.bagEquals  thrpt   20  16872.887 ±  46.903  ops/ms
IntBagEqualsTest.mapEquals  thrpt   20  15838.773 ± 103.729  ops/ms
```
After using allSatisfyKeyValue in primitive Bag equals:
```
Benchmark                    Mode  Cnt      Score     Error   Units
IntBagEqualsTest.bagEquals  thrpt   20  51903.988 ± 237.046  ops/ms
IntBagEqualsTest.mapEquals  thrpt   20  15964.766 ± 172.302  ops/ms
```
=> Optimize equals for primitive Bags using allSatisfyKeyValue on primitivePrimitive Maps

.mvn/maven.config
This reverts commit 985defb2df44bf46a8a2a653a00dc70a7579971b.
Adding --color broke the CodeQL build, which doesn't run on pull_request, and uses an auto-configured but old version of maven.
=> Revert "Add `--color=always` to .mvn/maven.config"

.gitattributes
In code reviews like #1606, the diffs are collapsed by default because files under .idea/ are considered generated sources (screenshot below).
Similar to the changes in #1608, I followed [GitHub's documentation](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github) on how to configure .gitattributes to control which files are considered generated.
Before:
After:
the diff will simply appear
=> Set .idea to linguist-generated=false in .gitattributes so that it shows up in code review diffs.

unit-tests/src/test/java/org/eclipse/collections/impl/SynchronizedRichIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/sorted/mutable/MutableSortedMapTestCase.java
Migrate to Junit5 friendly syntax - MutableSortedMapTestCase and SynchronizedRichIterableTest
@donraab / @motlin - 1 more pls :-)
=> Migrate to Junit5 friendly syntax - 2 more classes

.github/workflows/coverage.yaml, .github/workflows/mutation.yml, .github/workflows/pull-request.yml
Consistently run `mvn --non-recursive wrapper:wrapper -Dmaven=3.9.6` without extra flags to make sure we're using a known version, and then run `./mvnw --color=always` afterwards.
=> Consistently use `./mvnw --color=always` from GitHub workflows.

unit-tests/src/test/java/org/eclipse/collections/impl/map/sorted/mutable/UnmodifiableTreeMapTest.java
Before:
```
❯ rg '@Test\(expected' | wc -l
869
```
After:
❯ rg '@Test\(expected' | wc -l
835
I could use help with these @Desislav-Petrov
=> Refactor UnmodifiableTreeMapTest to use assertThrows instead of @Test(expected).

unit-tests-java8/src/test/java/org/eclipse/collections/test/IterableTestCase.java
This one is a bit odd because it's an obvious bug fix inside test utility that I'm contributing without new tests. I ran into this while writing some Map tests that I'm about to put up in a separate PR, so I know that the fix helps.
=> Fix NullPointerException in IterableTestCase.assertEquals

.github/workflows/pull-request.yml, acceptance-tests/pom.xml, eclipse-collections-api/pom.xml, eclipse-collections-code-generator-maven-plugin/pom.xml, eclipse-collections-code-generator/pom.xml, eclipse-collections-forkjoin/pom.xml, eclipse-collections-testutils/pom.xml, eclipse-collections/pom.xml, pom.xml, serialization-tests/pom.xml, test-coverage/pom.xml, unit-tests-java8/pom.xml, unit-tests/pom.xml
I have two changes here:
- Separating maven plugins into profiles and only enabling the relevant profiles in the relevant workflows
- Adding the GitHub shared action for caching the .m2 directory
These are only related in that they both are intended to speed up the build and they both were created by comparing with another open source GitHub workflow which is written in this style.
The maven profile thing creates a third related change, splitting the "test" configuration into separate test, enforcer, and dependency:analyze-only jobs.
If this is too much, I can definitely split out the caching, and possibly more.
=> Add maven profiles and caching to speed up builds.

CONTRIBUTING.md
Eclipse Collections 12.x will be compatible with Java 11+. The project build failed when I use java 1.8.
=> fix java version in contributing doc

docs/2-Collection_Containers.adoc
Improvements to the "Primitive sets" section of the [2-Collection_Containers](https://github.com/eclipse/eclipse-collections/docs/2-Collection_Containers) doc
=> Fix typo and punctuation details in Primitive set doc

eclipse-collections-forkjoin/pom.xml, eclipse-collections-forkjoin/src/test/java/org/eclipse/collections/impl/forkjoin/FJIterateTest.java
Moves **forkjoin** module to Junit5
* Moves any imports
* Fixes incompatible syntax for assertEquals
* Removes the junit4 dependency as no longer needed
cc @motlin
=> Move forkjoin module to Junit5

unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2AdditionalTest.java
These four tests are flaky. They fail a small percentage of the time and I usually rerun them and move on. I finally looked at the code and they are clearly not thread-safe. They all run some form of `.parallelStream().collect(Collectors2.sumBy*(), ...)`.
The `Collectors2.sumBy*()` methods all delegate directly to a non-thread-safe map, so this is a pretty clear case of non-thread-safe code. I have no opinion on whether the Collectors ought to be thread-safe; if so let's file an issue to fix them separately. For now, I just want to remove the tests since they waste time.
There are serial versions of the same tests, so deleting the tests does not decrease coverage.
cc @donraab
=> Delete four flaky tests: Collectors2AdditionalTest.sumBy*Parallel().

eclipse-collections-api/src/main/java/org/eclipse/collections/api/set/SetIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/set/sorted/SortedSetIterable.java
=> Fix incorrect Javadoc for SortedSetIterable.intersect(),SetIterable.intersect() .

pom.xml
Before, thousands of lines of tests running:
```console
13:22:26:761 [INFO] --- surefire:3.4.0:test (default-test) @ unit-tests ---
13:22:26:765 [INFO] Tests will run in random order. To reproduce ordering use flag -Dsurefire.runOrder.random.seed=358056349203
13:22:26:793 [INFO] Surefire report directory: /home/runner/work/eclipse-collections/eclipse-collections/unit-tests/target/surefire-reports
13:22:26:793 [INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
13:22:26:797 [INFO] 
13:22:26:797 [INFO] -------------------------------------------------------
13:22:26:798 [INFO]  T E S T S
13:22:26:798 [INFO] -------------------------------------------------------
13:22:37:527 [INFO] Running …
```
=> Configure maven-surefire-plugin printSummary to false, to stop logging successful tests.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/tuple/Triple.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/block/procedure/SumOfDoubleProcedure.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/block/procedure/SumOfFloatProcedure.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/block/procedure/SumOfIntProcedure.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/block/procedure/SumOfLongProcedure.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/parallel/Batch.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/IntervalUtils.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/immutable/ImmutableTreeMap.java, serialization-tests/src/test/java/org/eclipse/collections/impl/multimap/bag/sorted/immutable/ImmutableSortedBagMultimapImplSerializationTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collection/mutable/primitive/AbstractBooleanIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/collection/mutable/primitive/AbstractMutableBooleanStackTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractByteSetTestCase.java
Another example based on #1687.
This was created with the command:
`mvn spotless:apply --activate-profiles 'spotless-apply,spotless-java-sort-imports'`
I was using this command to fix up the imports in my own changes, but it found a few older examples of files with unsorted imports, and files that don't end with a newline.
=> Fix static analysis violations.

pom.xml
When working locally, I break the Checkstyle build frequently and manually fix it up. Probably the most frequently violated rule is unused imports. This feels silly, there are lots of CLI tools that can sort and minimize imports.
In other projects, at work and now in side projects, I've had good results with [Spotless](https://github.com/diffplug/spotless). It's a linter runner that unifies the configuration of other linters. For example, it allows configuring consistent on/off annotations to disable formatters on sections of code, even if the formatters were written by different authors. It also allows chaining linters For example, it can be configured to format code with an opinionated formatter like prettier, and then sort imports differently afterwards.
In this PR, I'm adding a few …
=> Add Spotless maven profiles.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java
- Updated top of RichIterable javadoc to include method categories with links to methods
- Created region/endregion sections to correspond to method categories
=> Categorize methods in RichIterable using region/endregion comments.

.github/dependabot.yml, .github/workflows/mutation.yml, .github/workflows/pull-request.yml
Another example based on #1687, to show off the kind of thing that Spotless can do, this time in a language other than Java.
This was created with the command:
`mvn spotless:apply --activate-profiles 'spotless-apply,spotless-yaml'`
=> Format yaml files using Spotless.

eclipse-collections-api/pom.xml, eclipse-collections/pom.xml, pom.xml
Moved bnd-maven-plugin configuration to the release-artifacts profile so that it will affect released jars but will otherwise not affect local development.
cc @fipro78
=> Move bnd-maven-plugin to a profile.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java
The emojis are only used in custom code folding region comments and Javadoc. They appear ok in IntelliJ in source editor/structure view, Javadoc in browser, in GitHub code browser, in raw source form view on GitHub, and in less and vi on MacOS. They can also be highlighted and used to search in both IntelliJ and browser.
Refer to [this blog](https://donraab.medium.com/associating-method-categories-with-emojis-in-intellij-and-javadoc-a82aebe1e903?source=friends_link&sk=d896106bcb8a6de06719edab75215281) to see how they appear in IntelliJ Structure View and Javadoc in browser and in plain and rendered reader mode in IntelliJ.
=> Shorten category names and add emojis.

.github/workflows/pull-request.yml
We recently had a ["backwards" merge commit](https://github.com/eclipse/eclipse-collections/commit/cb4f64274e905492f0c70f9981a6097c718fad97) land on the master branch.
It's visible in the git history as the white arrow here.
I wrote and open sourced [a GitHub Action](https://github.com/marketplace/actions/forbid-merge-commits) to prevent this sort of thing. Its README has more details about why this is a problem and how folks get into this situation. When it happens, the error message is pretty helpful about how to fix up git history.
=> Add job forbid-merge-commits to .github/workflows/pull-request.yml.

pom.xml
See here: https://bugs.openjdk.org/browse/JDK-8212233
=> Change Javadoc JDK to 8 to work around Deploy build problems

.github/workflows/coverage.yaml, .github/workflows/mutation.yml, .github/workflows/pull-request.yml, .idea/misc.xml, eclipse-collections-api/pom.xml, eclipse-collections-code-generator-maven-plugin/pom.xml, eclipse-collections-code-generator/pom.xml, eclipse-collections-forkjoin/pom.xml, eclipse-collections-testutils/pom.xml, eclipse-collections/pom.xml, pom.xml, unit-tests-java8/pom.xml
Updating the minimum version of Eclipse Collections to Java 17. The Java 11 release build has failed due to the `Javadoc:jar` target not succeeding. This has been a known issue which was supposedly fixed but not successfully backported to Java 11. Reference OpenJDK ticket: https://bugs.openjdk.org/browse/JDK-8212233
Please note: If you refer to previous commits merged today, you can observe that all the mentioned solutions like `<source>8</source>` were tried. 
Example Release builds are here: https://ci.eclipse.org/collections/job/deploy/168/console
Logs for reference:
```
03:34:48:044 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.11.2:jar (attach-javadocs) on project eclipse-collections-code-generator: MavenReportException: Error while generating …
```
=> Upgrade minimum version to Java 17

eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMapUnsafe.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/UnifiedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/strategy/mutable/UnifiedMapWithHashingStrategy.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/mutable/MapTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/UnifiedMapTest.java
This PR updates Map.merge to correctly handle entries with null values by bypassing the remapping function and directly storing the provided value.
The change was introduced in PR #1542 and violates the optional Map.merge contract, deviating from the previous behavior of maps affected by mentioned PR.
=>  Fix Map.merge to handle null values without invoking remapping function

eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/UnifiedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/strategy/mutable/UnifiedMapWithHashingStrategy.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/mutable/MutableMapIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bimap/mutable/UnmodifiableBiMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/MutableMapIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/UnmodifiableMutableMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/sorted/mutable/UnmodifiableTreeMapTest.java
I have a branch where I've added a bunch of tests and most of them pass, but it turns out that updateValue() and updateValueWith() actually have the bug so I figured I'd fix it first.
=> Fix updateValue exception safety in UnifiedMap and UnifiedMapWithHashingStrategy.
