eclipse-collections/eclipse-collections

about.html, eclipse-collections-api/src/main/resources/LICENSE-EDL-1.0.txt, eclipse-collections-api/src/main/resources/LICENSE-EPL-1.0.txt, eclipse-collections-api/src/main/resources/about.html, eclipse-collections-forkjoin/src/main/resources/LICENSE-EDL-1.0.txt, eclipse-collections-forkjoin/src/main/resources/LICENSE-EPL-1.0.txt, eclipse-collections-forkjoin/src/main/resources/about.html, eclipse-collections-testutils/src/main/resources/LICENSE-EDL-1.0.txt, eclipse-collections-testutils/src/main/resources/LICENSE-EPL-1.0.txt, eclipse-collections-testutils/src/main/resources/about.html, eclipse-collections/src/main/resources/LICENSE-EDL-1.0.txt, eclipse-collections/src/main/resources/LICENSE-EPL-1.0.txt, eclipse-collections/src/main/resources/about.html
Added about file and license files for release bundle.
=> Add about files for release.

pom.xml
Release build failed with missing distributionManagement element in parent.
=> Add release profile for GPG signing and OSSRH configurations to parent pom file.

eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/UnifiedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/strategy/mutable/UnifiedSetWithHashingStrategy.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/UnifiedMapTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/AbstractMutableSetTestCase.java
- Update the version number from 7.0.0 to 7.0.1.
- Bug fix in UnifiedSet$ChainedBucket.removeLongChain() method.
=> Changes for 7.0.1 bug fix release.

CONTRIBUTING.md, README.md
- Add a detailed contributor guide in CONTRIBUTING.md covering the CLA, GitHub issues, discussing changes, the build, semantic versioning, coding style, commit messages, and pull requests.
- Update README.md with links to community resources and for consistency with other changes.
=> Create CONTRIBUTING.md and add community references to README.md

acceptance-tests/pom.xml, eclipse-collections-api/pom.xml, eclipse-collections-code-generator-ant/pom.xml, eclipse-collections-code-generator-maven-plugin/pom.xml, eclipse-collections-code-generator/pom.xml, eclipse-collections-forkjoin/pom.xml, eclipse-collections-testutils/pom.xml, eclipse-collections/pom.xml, jmh-scala-tests/pom.xml, jmh-tests/pom.xml, junit-trait-runner/pom.xml, performance-tests/pom.xml, pom.xml, scala-unit-tests/pom.xml, serialization-tests/pom.xml, unit-tests-java8/pom.xml, unit-tests/pom.xml
Cherry pick a few commits from master that are necessary to run automated release builds.
- Update the version to 7.0.1-SNAPSHOT
- Consistently configure plugins and version numbers in the parent pom.
=> Prepare the build in the 7.0.x branch for releasing 7.0.1.

.gitignore
Cherry pick the same change to 7.0.x so that service release build can ignore .maven folder.
=> Add .maven folder to .gitignore file.

eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/Verify.java, eclipse-collections-testutils/src/test/java/org/eclipse/collections/impl/test/VerifyTest.java
Signed-off-by: Bhavana Hindupur <bhavana.hindupur@gmail.com>
=> Implement Verify.assertNotInstanceOf. #28

eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/mutable/AbstractMutableBiMap.java, unit-tests/src/test/java/org/eclipse/collections/impl/bimap/mutable/HashBiMapTest.java
I added a third test to check for key preservation when we use forcePut().
=> Fix memory leak in HashBiMap. 

eclipse-collections-code-generator/src/main/resources/impl/bag/mutable/primitiveHashBag.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMapWithHashingStrategy.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/objectPrimitiveHashMapWithHashingStrategyTest.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/primitive/ObjectBooleanHashMapWithHashingStrategy.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/primitive/ObjectBooleanHashMapWithHashingStrategyTest.java
Signed-off-by: jajodr <ranjan.jajodia@gs.com>
=> Bug Fix for Primitive Hash Maps With Hashing Strategy

README.md
Add link to Kata for better discoverability.
=> Add link to Kata from README.md.

CONTRIBUTING.md, RELEASE_NOTE_DRAFT.md
(Ignore  d3d00c9 which is part of PR #71 )
- Added RELEASE_NOTE_DRAFT.md that includes changes for 7.1.0 committed so far.
- Added an instruction to write a draft release note to CONTRIBUTING.md.
=> Add an instruction to write a draft release note to CONTRIBUTING.md.

RELEASE_NOTE_DRAFT.md
Could you please merge this before starting to merge other changes. Folks should start populating this along with their changes.
=> Initialize draft release note for 8.0.0.

RELEASE_NOTE_DRAFT.md, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/Multimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/AbstractImmutableMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/AbstractMutableMultimap.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/AbstractImmutableMultimapTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/AbstractMultimapTestCase.java
=> Implement keySet() on Multimap.

eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableSingletonBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/fixed/SingletonMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/immutable/ImmutableSingletonMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/immutable/primitive/ImmutableFalseSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/immutable/primitive/ImmutableTrueSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/MapIterate.java, jmh-tests/src/main/java/org/eclipse/collections/impl/jmh/map/ScalaAnyRefMapGetTest.java, jmh-tests/src/main/java/org/eclipse/collections/impl/jmh/map/ScalaImmutableMapGetTest.java, jmh-tests/src/main/java/org/eclipse/collections/impl/jmh/map/ScalaMutableMapGetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/AnagramTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableSingletonBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collection/mutable/CollectionAdapterAsUnmodifiableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collection/mutable/UnmodifiableMutableCollectionTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/ListIterateTest.java
=> Fix ecj compilation issues.

eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/abstractPrimitiveListTestCase.stg, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/primitive/AbstractBooleanListTestCase.java
Signed-off-by: guoci <zguoci@gmail.com>
=> Fix bug in primitiveArrayList.reverseThis()

RELEASE_NOTE_DRAFT.md, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/primitive/BooleanArrayList.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/primitive/AbstractBooleanListTestCase.java
Following code in eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg
Signed-off-by: guoci <zguoci@gmail.com>
=> Add static method BooleanArrayList.newWithNValues

RELEASE_NOTE_DRAFT.md
Signed-off-by: guoci <zguoci@gmail.com>
=> Add bugfix description in RELEASE_NOTE_DRAFT.md

unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java
Please pull this PR to fix failing builds.
=> Delete tests with compile errors from Collectors2Test.

checkstyle-suppressions.xml, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java
=> Add JavaDoc to Collectors2

RELEASE_NOTE_DRAFT.md
This is what we're going to use for 8.0.0-M1 release note. 
- Updated version number to 8.0.0-M1
- Added changes for #112
=> Update RELEASE_NOTE_DRAFT.md for 8.0.0-M1 release.

RELEASE_NOTE_DRAFT.md
Signed-off-by: Hiroshi Ito <Hiroshi.Ito@gs.com>
=> Update RELEASE_NOTE_DRAFT.md for 8.0.0-M2 release.

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java
=> Fix issues in Collectors2 Javadoc.

eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Multimaps.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/MultimapsTest.java
Signed-off-by: Hiroshi Ito <Hiroshi.Ito@gs.com>
=> Implement of() methods on Multimaps

RELEASE_NOTE_DRAFT.md, eclipse-collections-code-generator/src/main/resources/api/block/function/primitiveFunction.stg, eclipse-collections-code-generator/src/main/resources/api/block/function/primitiveFunction0.stg, eclipse-collections-code-generator/src/main/resources/api/block/function/primitiveToObjectFunction.stg, eclipse-collections-code-generator/src/main/resources/api/block/function/primitiveToPrimitiveFunction.stg, eclipse-collections-code-generator/src/main/resources/api/block/procedure/objectPrimitiveProcedure.stg, eclipse-collections-code-generator/src/main/resources/api/block/procedure/primitiveProcedure.stg, findbugs-exclude.xml
The changes are corresponding to issue #125 and #126.
=> Change primitive functional interfaces to extend the corresponding JDK functional interfaces.

README.md, RELEASE_NOTE_DRAFT.md
* Update README.md links to point to 8.0.0.
* Update RELEASE_NOTE_DRAFT.md for 8.1.0 release.
=> Update README.md and RELEASE_NOTE_DRAFT.md after 8.0.0 release.

pom.xml
Signed-off-by: Hiroshi Ito <Hiroshi.Ito@gs.com>
=> Cherry pick Javadoc fixes to 8.0.x branch.

pom.xml
Signed-off-by: Hiroshi Ito <Hiroshi.Ito@gs.com>
=> Cherry pick Javadoc fixes to 7.1.x branch.

eclipse-collections-code-generator/src/main/resources/impl/stack/abstractPrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/immutable/immutablePrimitiveArrayStack.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/mutable/primitiveArrayStack.stg
Signed-off-by: Kristen O'Leary kristen.oleary@gs.com
=> Add Abstract<primitive>Stacks.

pom.xml
It turned out the branches I created earlier were stemmed from wrong place (master). I have re-created correct branches and re-submitting the PRs accordingly.
=> [Re-submit] Cherry pick Javadoc fixes to 7.1.x branch. 

docs/guide.md
Merge remote-tracking branch 'upstream/master'
=> Update reference guide.

docs/guide.md
=> Fix minor issues in guide.md.

docs/guide.md
=> Add table of contents to guide.md.

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2AdditionalTest.java
=> Implement flatCollect on Collectors2.

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/SummaryStatistics.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2AdditionalTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/SummaryStatisticsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/ValueHolder.java
=> Implement SummaryStatistics and Collectors2.summarizing.

RELEASE_NOTE_DRAFT.md, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/BigDecimalSummaryStatistics.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/BigIntegerSummaryStatistics.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/BigDecimalSummaryStatisticsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/BigIntegerSummaryStatisticsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2AdditionalTest.java
=> Implement BigDecimalSummaryStatistics and BigIntegerSummaryStatistics.

eclipse-collections-api/pom.xml
=> Export all packages of eclipse-collections-api in manifest.mf.

README.md, RELEASE_NOTE_DRAFT.md
=> Update README.md and RELEASE_NOTE_DRAFT.md.

eclipse-collections/src/main/java/org/eclipse/collections/impl/block/function/CaseFunction.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/block/procedure/CaseProcedure.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/CaseProcedureTest.java
=> Optimize and increase test coverage for CaseFunction and CaseProcedure.

eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/primitive/BooleanHashBag.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/primitive/AbstractMutableBooleanBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2AdditionalTest.java
=> Make Collectors2.sumBy tests consistent for groupBy keys.

unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableSingletonBagTest.java
=> Add tests for detectOptional and detectWithOptional to unit test suite.

unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/SynchronizedRichIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/UnmodifiableRichIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/collection/mutable/CollectionAdapterTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2AdditionalTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/stack/StackIterableTestCase.java
=> Change StackIterableTestCase to extend AbstractRichIterableTestCase.

RELEASE_NOTE_DRAFT.md, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/BigDecimalSummaryStatistics.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/BigIntegerSummaryStatistics.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/SummaryStatistics.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/BigDecimalSummaryStatisticsSeralizationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/BigIntegerSummaryStatisticsSeralizationTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2AdditionalTest.java
=> Implement sumByBigDecimal and sumByBigInteger on Collectors2.

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/SerializableDoubleSummaryStatistics.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/SerializableIntSummaryStatistics.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/SerializableLongSummaryStatistics.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/SummaryStatistics.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableDoubleSummaryStatisticsSeralizationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableIntSummaryStatisticsSeralizationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableLongSummaryStatisticsSeralizationTest.java, serialization-tests/src/test/java/org/eclipse/collections/impl/collector/SummaryStatisticsSeralizationTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableDoubleSummaryStatisticsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableIntSummaryStatisticsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/SerializableLongSummaryStatisticsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/SummaryStatisticsTest.java
=> Make SummaryStatistics Serializable.

eclipse-collections-code-generator/src/main/resources/api/primitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/map/abstractMutablePrimitiveValuesMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/primitiveHashSet.stg, eclipse-collections-code-generator/src/main/resources/test/collection/mutable/abstractPrimitiveIterableTestCase.stg
=> Implement select and reject with targets on primitive iterables.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/PrimitiveIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/Bag.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/sorted/MutableSortedBag.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/collection/ImmutableCollection.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/collection/MutableCollection.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/MutableList.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MapIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MutableMapIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/primitive/PrimitiveObjectMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/MutableMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/set/MutableSet.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/set/sorted/MutableSortedSet.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/stack/StackIterable.java, eclipse-collections-code-generator/src/main/resources/api/map/objectPrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/primitivePrimitiveMap.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/AbstractRichIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Sets.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/ArrayIterate.java
=> Update and improve JavaDoc in high level interfaces.

eclipse-collections-code-generator/src/main/resources/api/primitiveIterable.stg
=> Improve generated JavaDoc in primitiveIterable.stg.

eclipse-collections-code-generator/src/main/resources/copyright.stg, eclipse-collections-code-generator/src/main/resources/impl/block/function/primitiveCaseFunction.stg, eclipse-collections-code-generator/src/main/resources/test/block/function/primitiveCaseFunctionTest.stg, unit-tests/src/test/java/org/eclipse/collections/impl/block/function/primitive/BooleanCaseFunctionTest.java
=> Implement primitive case functions.

serialization-tests/src/test/java/org/eclipse/collections/impl/block/function/primitive/PrimitiveCaseFunctionSerializationTest.java
=> Implement serialization tests for primitive case functions.

RELEASE_NOTE_DRAFT.md, eclipse-collections-code-generator/src/main/resources/impl/block/procedure/primitiveCaseProcedure.stg, eclipse-collections-code-generator/src/main/resources/test/block/procedure/primitiveCaseProcedureTest.stg, serialization-tests/src/test/java/org/eclipse/collections/impl/block/procedure/primitive/PrimitiveCaseProcedureSerializationTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/primitive/BooleanCaseProcedureTest.java
=> Implement primitive case procedures.

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/fixed/ArrayAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/FastList.java
=> Implement spliterator on FastList and ArrayAdapter.

eclipse-collections-api/pom.xml, eclipse-collections/pom.xml, pom.xml
Back port fixes for the issues #49 , #152 , #172 .
=> Cherry pick changes for service release 7.1.1

eclipse-collections-api/pom.xml, eclipse-collections/pom.xml, pom.xml
Back port fixes for the issues #49 , #152 , #172 .
=> Cherry pick changes for service release 8.0.1

unit-tests/src/test/java/org/eclipse/collections/impl/block/CheckedBlocksTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/predicate/MapEntryPredicateTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/predicate/PairPredicateTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/ArrayListAdapterTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/stack/mutable/ArrayStackTest.java
Signed-off-by: Gaurav Khurana <grv.khurana@gmail.com>
=> Add unit test for PairPredicate.

eclipse-collections-code-generator/src/main/resources/api/primitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/copyrightAndOthers.stg, eclipse-collections-code-generator/src/main/resources/test/bag/immutable/immutablePrimitiveEmptyBagTest.stg, eclipse-collections-code-generator/src/main/resources/test/collection/mutable/abstractPrimitiveIterableTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/list/immutable/immutablePrimitiveEmptyListTest.stg, eclipse-collections-code-generator/src/main/resources/test/set/immutable/immutablePrimitiveEmptySetTest.stg, eclipse-collections-code-generator/src/main/resources/test/stack/immutable/immutablePrimitiveEmptyStackTest.stg, unit-tests/src/test/java/org/eclipse/collections/impl/set/immutable/primitive/ImmutableBooleanEmptySetTest.java
=> Implement averageIfEmpty and medianIfEmpty on primitive iterables.

README.md
Signed-off-by: Nicolas PERU <nicolas.peru@gmail.com>
=> Update README.md with Sonarqube badge

checkstyle-configuration.xml, eclipse-collections-code-generator/src/main/resources/test/map/mutable/objectPrimitiveHashMapTestCase.stg, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/primitive/ObjectBooleanHashMapWithHashingStrategyValuesTest.java
This should make it easier for contributors to send pull requests that conform to the project style.
Also, fix an offender.
=> Activate Checkstyle RequireThis module.

README.md
Preview is available here: https://github.com/nikhilnanivadekar/eclipse-collections/blob/master/README.md
=> Add Eclipse Collections logo in README.

p2-repository/org.eclipse.collections/osgi.bnd
Task-Url: https://github.com/eclipse/eclipse-collections/issues/319
Signed-off-by: bergmann <bergmann@mit.bme.hu>
=> [#319] Export all packages to OSGi as non-internal

docs/guide.md, p2-repository/pom.xml
Also add logo in reference guide.
=> Add new profiles for p2 releases

eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/UnifiedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/UnifiedSet.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/UnifiedMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/UnifiedSetTest.java
=> Implement UnifiedMap.trimToSize(), UnifiedSet.trimToSize(). 

eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Lists.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Maps.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Sets.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/SortedMaps.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/SortedSets.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/ListAdapterTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/MapAdapterTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/sorted/mutable/SortedMapAdapterTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/SetAdapterTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/sorted/mutable/SortedSetAdapterTest.java
=> Implement adapt on factory classes.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/ImmutableList.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/ListIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/MutableList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/immutable/AbstractImmutableList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/AbstractListAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/AbstractMutableList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/ArrayListAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/SynchronizedMutableList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/UnmodifiableMutableList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/ArrayListIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/ListIterate.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/AbstractImmutableListTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/ImmutableEmptyListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/AbstractListTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/UnmodifiableMutableListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/ListIterateTest.java
=> Implement distinctBy on ListIterable.

RELEASE_NOTE_DRAFT.md, eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/ListIterable.java
=> Add JavaDoc for distinctBy and updated RELEASE_NOTE_DRAFT.

eclipse-collections-api/pom.xml, eclipse-collections-forkjoin/pom.xml, eclipse-collections-testutils/pom.xml, eclipse-collections/pom.xml
=> Skip deploy all artifacts except p2 while running with performReleaseP2.

eclipse-collections-code-generator/src/main/resources/api/bag/immutablePrimitiveBag.stg, eclipse-collections-code-generator/src/main/resources/api/bag/mutablePrimitiveBag.stg, eclipse-collections-code-generator/src/main/resources/api/bag/primitiveBag.stg, eclipse-collections-code-generator/src/main/resources/api/collection/immutablePrimitiveCollection.stg, eclipse-collections-code-generator/src/main/resources/api/collection/mutablePrimitiveCollection.stg, eclipse-collections-code-generator/src/main/resources/api/lazyPrimitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/api/list/immutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/list/mutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/list/primitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/map/immutableObjectPrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/mutableObjectPrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/objectPrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/primitiveValuesMap.stg, eclipse-collections-code-generator/src/main/resources/api/primitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/api/set/immutablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/api/set/mutablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/api/set/primitiveSet.stg, eclipse-collections-code-generator/src/main/resources/api/stack/immutablePrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/api/stack/mutablePrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/api/stack/primitiveStack.stg, eclipse-collections-code-generator/src/main/resources/impl/lazy/abstractLazyPrimitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/impl/lazy/tapPrimitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/impl/utility/lazyPrimitiveIterate.stg, eclipse-collections-code-generator/src/main/resources/test/collection/mutable/abstractPrimitiveIterableTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/lazy/abstractLazyPrimitiveIterableTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/lazy/primitiveTapIterableTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/abstractObjectPrimitiveMapTestCase.stg, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/primitive/TapBooleanIterableTest.java
=> Implement tap on primitive iterables. Closes #311.

eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Maps.java
=> Fix Javadoc issue in Maps.

README.md
=> Updated readme.MD to point to 9.0.0.

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java
=> Implement countBy on Collectors2.

eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Strings.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/StringsTest.java
=> Implement factory class for Strings.

RELEASE_NOTE_DRAFT.md, eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Lists.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderMutableListFactory.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/ListsTest.java
Signed-off-by: Jackie Haynes <jackie.haynes@gs.com>
=> Implement multiReader list factory #338

eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/list/MutableListFactory.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MutableListFactoryImpl.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/ListsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/SetsTest.java
Signed-off-by: Bhavana Hindupur <bhavana.hindupur@gmail.com>
=> Add withInitialCapacity to Lists.mutable.

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderMutableListFactory.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/ListsTest.java
Signed-off-by: Bhavana Hindupur <bhavana.hindupur@gmail.com>
=> Implement withInitialCapacity on MultiReader.

eclipse-collections-code-generator/src/main/resources/api/list/immutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/list/mutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/list/primitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveEmptyList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveSingletonList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/synchronizedPrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/unmodifiablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/test/list/immutable/abstractImmutablePrimitiveListTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/abstractPrimitiveListTestCase.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/string/immutable/CharAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/string/immutable/CodePointAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/string/immutable/CodePointList.java
=> Implement zip on primitive lists. Closes #308.

eclipse-collections-code-generator/src/main/resources/api/collection/mutablePrimitiveCollection.stg, eclipse-collections-code-generator/src/main/resources/impl/bag/mutable/primitiveHashBag.stg, eclipse-collections-code-generator/src/main/resources/impl/collection/mutable/abstractSynchronizedPrimitiveCollection.stg, eclipse-collections-code-generator/src/main/resources/impl/collection/mutable/abstractUnmodifiablePrimitiveCollection.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/test/bag/mutable/unmodifiablePrimitiveBagTest.stg, eclipse-collections-code-generator/src/main/resources/test/collection/mutable/abstractMutablePrimitiveCollectionTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/unmodifiablePrimitiveListTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/objectPrimitiveHashMapValuesTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/primitivePrimitiveHashMapValuesTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/synchronizedObjectPrimitiveMapValuesTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/synchronizedPrimitivePrimitiveMapValuesTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/unmodifiableObjectPrimitiveMapValuesTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/unmodifiablePrimitiveBooleanMapKeySetTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/unmodifiablePrimitiveObjectMapKeySetTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/unmodifiablePrimitivePrimitiveMapKeySetTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/unmodifiablePrimitivePrimitiveMapValuesTest.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/unmodifiablePrimitiveSetTest.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/primitive/BooleanArrayList.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/primitive/AbstractBooleanListTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/primitive/UnmodifiableBooleanListTest.java
=> Implement removeIf for mutable primitive collections.

eclipse-collections/src/main/java/org/eclipse/collections/impl/map/strategy/mutable/UnifiedMapWithHashingStrategy.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/strategy/mutable/UnifiedMapWithHashingStrategyTest.java
Signed-off-by: Patrick Ekel <patrick.ekel@utah.edu>
=> Implement trimToSize on UnifiedMapWithHashingStrategy. Closes #370.

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java
Signed-off-by: TheLoneKing <dkumar.kovai@gmail.com>
=> Implement groupByEach Collector on Collectors2. Resolves #362

eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/ListIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/RandomAccessListIterate.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/ListIterateTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/internal/RandomAccessListIterateTest.java
=> Implement collectWithIndex on ListIterate and RandomAccessListIterate.

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java
Signed-off-by: TheLoneKing <dkumar.kovai@gmail.com>
=> Implement groupByUniqueKey Collector on Collectors2. Resolves #363

site/ru/index.html
Signed-off-by: Vladimir Zakharov <vladimir.zakharov@gs.com>
=> Fixed typos and style for the Russian translation of the web page

site/index.html, site/ja/index.html, site/pt-br/index.html
#382   - PR with the portuguese translation
Signed-off-by: Daniel-Dos <daniel.dias.analistati@gmail.com>
=> Add translation portugues - pt-br.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/Bag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableEmptyBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableSingletonBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/SynchronizedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/UnmodifiableBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/SynchronizedSortedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/UnmodifiableSortedBag.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/bag/BagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableEmptyBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableSingletonBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MutableBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/SynchronizedBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/UnmodifiableBagTest.java
=> Implement collectWithOccurrences on Bags.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/Bag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableEmptyBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableSingletonBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/SynchronizedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/UnmodifiableBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/SynchronizedSortedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/UnmodifiableSortedBag.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/bag/BagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableEmptyBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableSingletonBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MutableBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/SynchronizedBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/UnmodifiableBagTest.java
=> Fix spelling of occurrences.

eclipse-collections-code-generator/src/main/resources/api/list/immutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/list/mutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/list/primitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/ordered/orderedPrimitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/api/ordered/reversiblePrimitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/api/stack/immutablePrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/api/stack/mutablePrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/api/stack/primitiveStack.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/synchronizedPrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/unmodifiablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/mutable/synchronizedPrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/mutable/unmodifiablePrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/test/list/immutable/abstractImmutablePrimitiveListTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/abstractPrimitiveListTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/stack/mutable/abstractPrimitiveStackTestCase.stg
=> Implement collectWithIndex on primitive ordered iterables.

eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMapUnsafe.java
=> fix EntrySet.removeIf concurrency

eclipse-collections-code-generator/src/main/resources/api/bag/primitiveBag.stg, eclipse-collections-code-generator/src/main/resources/test/bag/immutable/abstractImmutablePrimitiveBagTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/bag/mutable/abstractMutablePrimitiveBagTestCase.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/AbstractBag.java
=> Implement toStringOfItemToCount on primitive Bags.

unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/Procedures2Test.java
=> Fix summarizeFloat in Procedures2Test.

eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderMutableBagFactory.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Bags.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/BagsTest.java
=> Add multiReader factories to Bags #338

site/ja/index.html
This is for issue https://github.com/eclipse/eclipse-collections/issues/399
=> Translate menu of Japanese site #399

eclipse-collections-code-generator/src/main/resources/impl/set/mutable/primitiveHashSet.stg
=> Make Primitive Hash Sets non-final. Closes #453.

eclipse-collections-code-generator/src/main/resources/impl/bag/mutable/primitiveHashBag.stg, eclipse-collections-code-generator/src/main/resources/impl/bag/mutable/synchronizedPrimitiveBag.stg, eclipse-collections-code-generator/src/main/resources/impl/bag/mutable/unmodifiablePrimitiveBag.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/synchronizedPrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/unmodifiablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/synchronizedObjectPrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/synchronizedPrimitiveObjectMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/synchronizedPrimitivePrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/unmodifiableObjectPrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/unmodifiablePrimitiveObjectMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/unmodifiablePrimitivePrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/synchronizedPrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/unmodifiablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/mutable/primitiveArrayStack.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/mutable/synchronizedPrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/mutable/unmodifiablePrimitiveStack.stg
=> Make primitive classes non-final. Closes #459.

eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/Verify.java, eclipse-collections-testutils/src/test/java/org/eclipse/collections/impl/test/VerifyTest.java
=> Implement assertPostSerializedEqualsHashCodeAndToString on Verify.

eclipse-collections-code-generator/src/main/resources/api/bag/mutablePrimitiveBag.stg, eclipse-collections-code-generator/src/main/resources/api/collection/mutablePrimitiveCollection.stg, eclipse-collections-code-generator/src/main/resources/api/list/mutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/set/mutablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/api/stack/mutablePrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/impl/bag/mutable/primitiveHashBag.stg, eclipse-collections-code-generator/src/main/resources/impl/bag/mutable/synchronizedPrimitiveBag.stg, eclipse-collections-code-generator/src/main/resources/impl/bag/mutable/unmodifiablePrimitiveBag.stg, eclipse-collections-code-generator/src/main/resources/impl/collection/mutable/synchronizedPrimitiveCollection.stg, eclipse-collections-code-generator/src/main/resources/impl/collection/mutable/unmodifiablePrimitiveCollection.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/synchronizedPrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/unmodifiablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMapWithHashingStrategy.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveBooleanHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitivePrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/primitiveHashSet.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/synchronizedPrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/unmodifiablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/mutable/primitiveArrayStack.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/mutable/synchronizedPrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/mutable/unmodifiablePrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/test/collection/mutable/abstractMutablePrimitiveCollectionTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/stack/mutable/abstractMutablePrimitiveStackTestCase.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/primitive/ByteHashSet.java
=> Implement newEmpty() on MutablePrimitiveCollection. Closes #440.

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java
Signed-off-by: TheLoneKing <dkumar.kovai@gmail.com>
=> Implement aggregateBy Collector on Collectors2. Resolves #361

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java
Hi all, I've implemented the code and unit test for countByEach for #478 in Collectors2.  Please let me know your comments.  Thanks!
=> Implement and unit test countByEach

site/cn/index.html, site/fr/index.html, site/index.html, site/ja/index.html, site/pt-br/index.html, site/ru/index.html
I also made some minor fixes in site files in second commit.
=>  Add reference guide and source code sections in Japanese site.

eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMapUnsafe.java
Make removeIf/removeAll a bit more predictable
=> Fix concurrent map iterator with size close to zero

README.md, docs/guide.md
Sets links to live 9.2 version replacing 8.0.0 with 9.2.0 in *.md
Signed-off-by: Leonardo Lima <leomrlima@gmail.com>
=> Sets links to live 9.2 version

eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MutableMapIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/mutable/UnmodifiableBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/AbstractSynchronizedMapIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/UnmodifiableMutableMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/mutable/UnmodifiableTreeMap.java
This is for issue https://github.com/eclipse/eclipse-collections/issues/428
=> Fix #428. Wildcard type in MutableMapIterable#putPair & add methods.

jmh-tests/src/main/java/org/eclipse/collections/impl/jmh/IntListJMHTest.java
=> Updated IntListJMHTest to include benchmarks using IntStream.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/MutableMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/AbstractSynchronizedMultimap.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/AbstractMutableMultimapTestCase.java
This is similar to https://github.com/eclipse/eclipse-collections/pull/522
=> Wildcard type in MultableMultimap#putAllPairs & add methods

p2-repository/pom.xml
Fixes #535
Signed-off-by: Gunnar Wagenknecht <gunnar@wagenknecht.org>
=> Update Tycho Version to 1.2.0

eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Multimaps.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/MultimapsTest.java
Signed-off-by: Breno Pessoa <brenopessoamelo@gmail.com>
=> Implement ImmutableSortedBagMultimapFactory in Multimaps. Fixes #528.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MutableOrderedMap.java
Hello everyone, i tried resolve the issue #517
Signed-off-by: Breno Pessoa <brenopessoamelo@gmail.com>
=> Fixes override methods on MutableOrderedMap #517

eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/UnifiedSet.java
=> Fix invalid cast in UnifiedSet.trimToSize().

eclipse-collections-code-generator/src/main/java/org/eclipse/collections/codegenerator/EclipseCollectionsCodeGenerator.java, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMapWithHashingStrategy.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitivePrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/primitiveHashSet.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/primitiveObjectHashMapTest.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/primitiveHashSetTest.stg, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/LongHashSetExtraTest.java
Aligns the rehashing algorithm with the primitive maps.
=> Fix multiple removes via iterator leaving no space in the set.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java, unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java
Closes #548 
Signed-off-by: alimcmaster1 <alimcmaster1@gmail.com>
=> Add getAny to RichIterable

eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/SerializeTestHelper.java
This pull request was created automatically as part of our ongoing efforts
at https://diffblue.com to implement refactorings. Feel free to leave feedback
here or contact us directly for any enquiries.
The developer in charge is @krobelus.
**Changes**:
- Replace try statements that close a resource in the finally block with a
try-with-resources statement [1].
[1] https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
=> Use try-with-resources

eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/set/strategy/ImmutableHashingStrategySetFactory.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/set/strategy/MutableHashingStrategySetFactory.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/strategy/immutable/ImmutableHashingStrategySetFactoryImpl.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/strategy/immutable/ImmutableUnifiedSetWithHashingStrategy.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/strategy/mutable/MutableHashingStrategySetFactoryImpl.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/HashingStrategySetsTest.java
Hi , this time i tried to help with the issue #539
Signed-off-by: Breno Pessoa <brenopessoamelo@gmail.com>
=> Implement ofInitialCapacity and withInitialCapacity in

eclipse-collections-code-generator/src/main/resources/api/map/mutableObjectPrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/mutablePrimitiveObjectMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/mutablePrimitivePrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/abstractMutableObjectPrimitiveMapTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/abstractMutablePrimitiveBooleanMapTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/abstractMutablePrimitiveObjectMapTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/abstractMutablePrimitivePrimitiveMapTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/unmodifiableObjectPrimitiveMapTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/unmodifiablePrimitiveBooleanMapTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/unmodifiablePrimitiveObjectMapTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/unmodifiablePrimitivePrimitiveMapTest.stg, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/primitive/AbstractMutableObjectBooleanMapTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/primitive/UnmodifiableObjectBooleanMapTest.java
Signed-off-by: Lorenzo Addazi <lorenzo.addazi@rcp-vision.com>
=> Implement withAllKeyValues on mutable primitive maps. Fixes #345

eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/package-info.java
Signed-off-by: Daniel Dias <daniel.dias.analistati@gmail.com>
this PR fix the issue #612
=> Fix org.eclipse.collections.api.list api doc incorrect . Fixes #612

pom.xml
- Fix configuration of maven-enforcer-plugin for requireMavenVersion.
- Upgrade eclipse-jarsigner-plugin from 1.1.3 to 1.1.5.
=> Upgrade versions of maven plugins.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java
Fix the broken build. I haven't run the tests yet.
=> Pull up several method bodies to default methods in api.

.travis.yml
I am raising this PR from the Sahara desert :smile:
=> Run EA build for all builds

eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/map/MutableMapFactory.java, eclipse-collections-code-generator/src/main/resources/api/factory/map/mutableObjectPrimitiveMapFactory.stg, eclipse-collections-code-generator/src/main/resources/api/factory/map/mutablePrimitiveObjectMapFactory.stg, eclipse-collections-code-generator/src/main/resources/api/factory/map/mutablePrimitivePrimitiveMapFactory.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/mutableObjectPrimitiveMapFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/mutablePrimitiveObjectMapFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/mutablePrimitivePrimitiveMapFactoryImpl.stg
=> Add ofInitialCapacity to primitive maps

eclipse-collections-testutils/pom.xml, eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/Verify.java
Reverts eclipse/eclipse-collections#682
=> Revert "Use Java 8 Base64 instead of apache"

README.md
=> Update README adding any, all, none examples.

README.md
=> Fix typo in README. Fixes #691

eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/bag/MutableBagFactory.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/list/FixedSizeListFactory.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/list/MutableListFactory.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/set/FixedSizeSetFactory.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/set/MutableSetFactory.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/stack/MutableStackFactory.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderMutableBagFactory.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MutableBagFactoryImpl.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/fixed/FixedSizeListFactoryImpl.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderMutableListFactory.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MutableListFactoryImpl.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/fixed/FixedSizeSetFactoryImpl.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/MultiReaderMutableSetFactory.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/MutableSetFactoryImpl.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/MutableStackFactoryImpl.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/BagsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/ListsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/SetsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/StacksTest.java
=> Implement fromStream(Stream) on collection factories. Close #694.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/bag/ImmutableBagFactory.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/list/ImmutableListFactory.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/set/ImmutableSetFactory.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/stack/ImmutableStackFactory.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/BagsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/ListsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/SetsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/StacksTest.java
=> Implement fromStream(Stream) on immutable collection factories.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutablePrimitiveObjectEmptyMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutablePrimitiveObjectHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutablePrimitiveObjectSingletonMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/synchronizedPrimitiveObjectMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/unmodifiablePrimitiveObjectMap.stg, eclipse-collections-code-generator/src/main/resources/test/map/abstractPrimitiveBooleanMapKeyValuesViewTest.stg, eclipse-collections-code-generator/src/main/resources/test/map/abstractPrimitiveObjectMapKeyValuesViewTestCase.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/AbstractRichIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/UnmodifiableRichIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/AbstractBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/mutable/UnmodifiableBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/block/procedure/BiMapCollectProcedure.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/AbstractSynchronizedRichIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/mutable/AbstractCollectionAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/mutable/AbstractMultiReaderMutableCollection.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/mutable/AbstractUnmodifiableMutableCollection.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/UnmodifiableMutableMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/ordered/mutable/UnmodifiableMutableOrderedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/mutable/UnmodifiableTreeMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableArrayStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/ArrayStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/SynchronizedStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/UnmodifiableStack.java, serialization-tests/src/test/java/org/eclipse/collections/impl/lazy/primitive/LazyIterableTestHelper.java, unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java
=> Add toBiMap() for RichIterable. Fixes #306

unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java
=> Add test coverage for minOptional and maxOptional on RichIterable

unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MutableBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/ArrayListIterateTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/ListIterateTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/internal/RandomAccessListIterateTest.java
=> Add test coverage for zip with an iterable.

eclipse-collections-code-generator/src/main/java/org/eclipse/collections/codegenerator/EclipseCollectionsCodeGenerator.java, eclipse-collections-code-generator/src/main/resources/api/list/primitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveEmptyList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveSingletonList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/synchronizedPrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/unmodifiablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/stream/primitive/primitiveSingletonSpliterator.stg, eclipse-collections-code-generator/src/main/resources/test/factory/primitiveListsTest.stg, eclipse-collections-code-generator/src/main/resources/test/list/immutable/abstractImmutablePrimitiveListTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/abstractPrimitiveListTestCase.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/IntInterval.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/string/immutable/CodePointAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/string/immutable/CodePointList.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/primitive/IntIntervalTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/string/immutable/CodePointAdapterTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/string/immutable/CodePointListTest.java
This is not ready to merge. As this is my first PR in this project i would appreciate if anyone could look at this and see if this is the right direction. I am more concerned with the concepts as with code style, etc
=> Primitive list stream

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/IntInterval.java
Leftover from #672 
@nikhilnanivadekar  - FYI
=> Assignment order of IntIntervalSpliterator

unit-tests/src/test/java/org/eclipse/collections/impl/list/primitive/IntIntervalTest.java
=> Add missing tests to IntIntervalTest.

README.md
=> Add OSGi bundle location to README.md.

eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBag.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBagTest.java
=> Increase test coverage of MultiReaderHashBag.

unit-tests/src/test/java/org/eclipse/collections/impl/string/immutable/CharAdapterTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/string/immutable/CodePointAdapterTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/string/immutable/CodePointListTest.java
=> Add test coverage to CharAdapter, CodePointAdapter and CodePointList.

unit-tests/src/test/java/org/eclipse/collections/impl/factory/ListsTest.java
=> Add missing test to ListsTest.

docs/guide.md
Modified guide.md and added examples for the following cases:
1. Creating Immutable Collections using .toImmutable()
2. Modifying Immutable Collections with methods like newWith(), newWithAll(), ...
The general tone and examples are referred from the blog that @donraab had shared in the issue discussion. Thank you for the informative article!
Signed-off-by: saurabhmj <saurabhjogalekar@gmail.com>
=> Implement #657: Documentation: Examples for Immutable Collections.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/RichIterableTestCase.java
Signed-off-by: TheLoneKing <dkumar.kovai@gmail.com>
=> Implement RichIterable.groupByAndCollect(). Resolves #47

site/cn/index.html, site/de/index.html, site/es/index.html, site/fr/index.html, site/index.html, site/ja/index.html, site/pt-br/index.html
Signed-off-by: HillmerCh <hilac@msn.com>
=> Spanish version of the Eclipse Collections site

.gitignore
Signed-off-by: Craig P. Motlin <cmotlin@gmail.com>
=> Improve .gitignore for maven.

p2-feature/org.eclipse.collections.feature/feature.xml, p2-feature/org.eclipse.collections.feature/pom.xml, p2-feature/pom.xml
* Ensures the correct EPLv1 license is downloaded
* Turns off signing for the feature
Signed-off-by: Zoltan Ujhelyi <zoltan.ujhelyi@incquerylabs.com>
=> Fixes generated Eclipse features #763

eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Multimaps.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/MultimapsTest.java
=> Changed internal variable name in Multimaps class for ImmutableSortedBagFactory

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/Interval.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/IntervalUtils.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/IntInterval.java, unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/ThrowingAppendable.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/IntervalTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/primitive/IntIntervalTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/math/MutableLong.java
=> Fix size edge case issues in Interval and IntInterval.

README.md, site/cn/index.html, site/de/index.html, site/fr/index.html, site/gr/index.html, site/ja/index.html, site/pt-br/index.html, site/ru/index.html
Signed-off-by: Thodoris Bais <thodoris.bais@gmail.com>
=> Greek translation of the Eclipse Collections site

README.md, site/cn/index.html, site/de/index.html, site/el/index.html, site/es/index.html, site/fr/index.html, site/index.html, site/ja/index.html, site/pt-br/index.html, site/ru/index.html
Signed-off-by: Thodoris Bais <thodoris.bais@gmail.com>
changes requested in #783
=> Minor fixes in the Greek translation

site/cn/index.html, site/el/index.html, site/es/index.html
Signed-off-by: Nikhil Nanivadekar <nikhil.nanivadekar@bnymellon.com>
=> Minor fixes to the website.

README.md
Signed-off-by: Lars Eckart <lars.eckart@gmail.com>
hello, my first contribution, I hope i got the eclipse account and contributer agreement done correctly :)
=> stop using deprecated compile dependency declaration

RELEASE_NOTE_DRAFT.md, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/UnifiedMap.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/mutable/MutableMapIterableTestCase.java
Signed-off-by: Digant Bhavsar <digantbhavsar@gmail.com>
=> Fix Bug #677 - Optimize removeIf() for UnifiedMap.

README.md, RELEASE_NOTE_DRAFT.md, site/cn/index.html, site/de/index.html, site/el/index.html, site/es/index.html, site/fr/index.html, site/index.html, site/ja/index.html, site/pt-br/index.html, site/ru/index.html
Signed-off-by: Nikhil Nanivadekar <nikhil.nanivadekar@bnymellon.com>
=> Prepare for 10.2.0 Release.

README.md
=> Add badge to README.md for GitHub Actions build.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MutableMapIterable.java
Signed-off-by: Kedar Joshi <kdar_joshi@yahoo.com>
Please see https://github.com/eclipse/eclipse-collections/issues/808#issuecomment-596024912.
=> Fix error in Javadoc generation

.travis.yml, eclipse-collections-api/src/main/java/org/eclipse/collections/api/PrimitiveIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/Bag.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/collection/FixedSizeCollection.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/collection/MutableCollection.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MapIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MutableMapIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/primitive/PrimitiveObjectMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/Multimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/ordered/OrderedIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/ordered/ReversibleIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/tuple/Pair.java, eclipse-collections-forkjoin/src/main/java/org/eclipse/collections/impl/forkjoin/FJIterate.java, eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/Verify.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/AbstractRichIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/mutable/AbstractMultiReaderMutableCollection.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Strings.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/parallel/ParallelIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/ArrayListIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/Iterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/ListIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/RandomAccessListIterate.java
Signed-off-by: Kedar Joshi <kdar_joshi@yahoo.com>
Please see https://github.com/eclipse/eclipse-collections/issues/808#issuecomment-596024912.
=> Fix Javadoc warnings

eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Multimaps.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/MultimapsTest.java
=> Increase test coverage in MultimapsTest.

eclipse-collections-code-generator/src/main/resources/test/collection/mutable/abstractPrimitiveIterableTestCase.stg, unit-tests/src/test/java/org/eclipse/collections/impl/collection/mutable/primitive/AbstractBooleanIterableTestCase.java
=> Add test coverage for reduceIfEmpty on primitive iterables.

.github/workflows/maven.yml
=> Update 14-ea to 14 in GitHub Action YAML.

eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/UnmodifiableRichIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/AbstractBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/mutable/UnmodifiableBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/AbstractSynchronizedRichIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/mutable/AbstractCollectionAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/mutable/AbstractMultiReaderMutableCollection.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/mutable/AbstractUnmodifiableMutableCollection.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/ArrayListAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/ListAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/RandomAccessListAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/UnmodifiableMutableMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/ordered/mutable/UnmodifiableMutableOrderedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/mutable/UnmodifiableTreeMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableArrayStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/ArrayStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/SynchronizedStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/UnmodifiableStack.java
=> Remove duplicate forEach overrides.

checkstyle-suppressions.xml, eclipse-collections-api/src/main/java/org/eclipse/collections/api/stack/StackIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableEmptyStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableNotEmptyStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableStackFactoryImpl.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableStackIterator.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableStackSerializationProxy.java, serialization-tests/src/test/java/org/eclipse/collections/impl/stack/immutable/ImmutableStackSerializationTest.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/stack/immutable/ImmutableStackTestCase.java
Signed-off-by: Craig P. Motlin <cmotlin@gmail.com>
=> Add singly-linked implementation of immutable stacks.

eclipse-collections/src/main/java/org/eclipse/collections/impl/factory/Multimaps.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/MultimapsTest.java
Signed-off-by: Alxander Goldberg <alexander.goldberg@bnymellon.com>
=> Fixed symmetry issues with factory methods in Multimaps factory. #826

eclipse-collections-api/src/main/java/org/eclipse/collections/api/block/function/Function2.java
Signed-off-by: Mikhail Krivoshein <mikhail.krivoshein@gmail.com>
=> Better JavaDocs for Function2. closes eclipse/eclipse-collections#832

eclipse-collections-api/src/main/java/org/eclipse/collections/api/block/function/Function3.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/collection/MutableCollection.java
Signed-off-by: Mikhail Krivoshein <mikhail.krivoshein@gmail.com>
=> Improve documentation of Function3 and MutableCollection#injectIntoWith. closes eclipse/eclipse-collections#839

eclipse-collections-api/src/main/java/org/eclipse/collections/api/bimap/MutableBiMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/ConcurrentMutableMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/FixedSizeMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MutableMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MutableMapIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MutableOrderedMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/sorted/MutableSortedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/mutable/SynchronizedBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/mutable/UnmodifiableBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/SynchronizedMutableMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/UnmodifiableMutableMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/ordered/mutable/OrderedMapAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/ordered/mutable/UnmodifiableMutableOrderedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/mutable/SynchronizedSortedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/mutable/UnmodifiableTreeMap.java, unit-tests/src/test/java/org/eclipse/collections/impl/bimap/mutable/AbstractMutableBiMapTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bimap/mutable/UnmodifiableBiMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMapUnsafeTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/MutableMapIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/UnmodifiableMutableMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/sorted/mutable/UnmodifiableTreeMapTest.java
Signed-off-by: Mohammed Aboullaite <aboullaite.mohammed@gmail.com>
This PR adds `withMap` a requested in #761
=> Add withMap to MutableMap

.github/workflows/maven.yml, .travis.yml
Since we're having trouble running checkstyle through travis in #842, I figured I'd upgrade maven to the latest version to rule that out and it's a good change anyway.
=> Upgrade maven from 3.6.1 to 3.6.3.

.github/workflows/acceptance.yml, .github/workflows/checkstyle.yml, .github/workflows/findbugs.yml, .github/workflows/javadoc.yml, .github/workflows/performance.yml, .github/workflows/unit.yml, README.md
Closes #811 
This converts most of the Travis build to GitHub Actions. 
cc: @motlin @nikhilnanivadekar @donraab
=> feat: enable GitHub actions

README.md
=> Fixed GitHub Actions Badges and Links in README. closes #854

README.md, README_EXAMPLES.md
=> Update README.md and add README_EXAMPLES.md.

.github/workflows/unit.yml
=> Disable 15-ea build.

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/Interval.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/IntervalTest.java
Closes #743
P.S. I am more than happy if you have any other suggestion for the method name.
=> feat: add fromToExclusive in Interval

README.md, site/cn/index.html, site/de/index.html, site/el/index.html, site/es/index.html, site/fr/index.html, site/hi/index.html, site/index.html, site/ja/index.html, site/pt-br/index.html
Hindi Translation of Eclipse Collections website #792
=> Hindi Translation of Eclipse Collections website #792

README.md
=> Fixing README URL for Hindi translation

eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/MutableBag.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/MutableBagIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/sorted/MutableSortedBag.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/FixedSizeList.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/MutableList.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/set/FixedSizeSet.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/set/MutableSet.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/set/MutableSetIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/set/sorted/MutableSortedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/SynchronizedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/SynchronizedSortedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/AbstractMutableList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/SynchronizedMutableList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/sorted/mutable/SynchronizedSortedSet.java
This PR implements the changes discussed in #822
=> Implement with(), without(), withAll(), withoutAll() as default methods

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutablePrimitiveObjectEmptyMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/synchronizedPrimitiveObjectMap.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/UnmodifiableRichIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/AbstractBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/AbstractBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/mutable/UnmodifiableBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/AbstractSynchronizedRichIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/mutable/AbstractMultiReaderMutableCollection.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/mutable/AbstractUnmodifiableMutableCollection.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/FastList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/UnmodifiableMutableMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/ordered/mutable/UnmodifiableMutableOrderedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/mutable/UnmodifiableTreeMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableArrayStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableEmptyStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/ArrayStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/SynchronizedStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/UnmodifiableStack.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/RichIterableTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/bag/BagTestCase.java
Signed-off-by: Alxander Goldberg <alexander.goldberg@bnymellon.com>
=> Added flatCollect support primitive collections #794

unit-tests/src/test/java/org/eclipse/collections/impl/PersonAndPetKataTest.java
=> Refactor PersonAndPetKatatTest to use newer APIs.

site/hi/index.html
The functional changes are only related to 10.2.0. The spacing and formatting changes are due to how the actual website repo and the GitHub repo mismatch. I have verified and the information is exactly the same.
I have already pushed the changes to published website. This PR is to make both the repos consistent.
https://www.eclipse.org/collections/hi/index.html
=> Update Hindi website with 10.2.0 information.

p2-feature/org.eclipse.collections.feature/feature.xml, p2-feature/org.eclipse.collections.feature/pom.xml, p2-feature/org.eclipse.collections.repository/category.xml, p2-feature/org.eclipse.collections.repository/pom.xml, p2-feature/pom.xml
=> Update version number to 10.3.0-SNAPSHOT

eclipse-collections-code-generator/src/main/resources/api/factory/list/mutablePrimitiveListFactory.stg, eclipse-collections-code-generator/src/main/resources/api/factory/set/mutablePrimitiveSetFactory.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/mutablePrimitiveListFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/mutablePrimitiveSetFactoryImpl.stg
=> Add withInitialCapacity() to primitive List and Set factories

eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/ListIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/SynchronizedMutableList.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/list/ListIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/AbstractListTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastListTest.java
=> Add forEachInBoth to ListIterable.

eclipse-collections-code-generator/src/main/resources/impl/bag/immutable/immutablePrimitiveSingletonBag.stg, eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveSingletonList.stg, eclipse-collections-code-generator/src/main/resources/impl/set/immutable/immutablePrimitiveSingletonSet.stg
=> Optimize collect methods for primitive Immutable Singleton Bags, Sets and Lists

eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/ListIterable.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/AbstractListTestCase.java
=> Add JavaDoc and null check to forEachInBoth.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/ImmutableBagIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/MutableBagIterable.java
Signed-off-by: Craig P. Motlin <cmotlin@gmail.com>
=> Pull up implementations of aggregateBy() as default methods.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/ImmutableMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/ImmutableMapIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MutableMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MutableMapIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/primitive/ImmutablePrimitiveObjectMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/primitive/MutablePrimitiveObjectMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/sorted/ImmutableSortedMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/stack/ImmutableStack.java, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/immutable/AbstractImmutableMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/AbstractMutableMapIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/immutable/AbstractImmutableSortedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableArrayStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableNotEmptyStack.java
=> Remove duplicate code for aggregateBy.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java, unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java
=> Added containsBy to RichIterable. Closes #919.

CONTRIBUTING.md
Context: [Link here](https://github.com/eclipse/eclipse-collections/pull/928#issuecomment-655375710)
=> Update build and checkstyle set up instructions in CONTRIBUTING guide

eclipse-collections-api/pom.xml, eclipse-collections-code-generator-maven-plugin/pom.xml, eclipse-collections-code-generator/pom.xml, eclipse-collections-forkjoin/pom.xml, eclipse-collections-testutils/pom.xml, eclipse-collections/pom.xml, pom.xml
Closes #360
Signed-off-by: Kedar Joshi <kdar_joshi@yahoo.com>
=> Upgrade maven-javadoc plugin to work with Java 9

.github/workflows/unit.yml
=> Disable maven download progress in Unit test GitHub actions. Closes #886

eclipse-collections-api/bnd.bnd, eclipse-collections-api/pom.xml, eclipse-collections/bnd.bnd, eclipse-collections/pom.xml, p2-feature/org.eclipse.collections.feature/pom.xml, p2-feature/org.eclipse.collections.repository/category.xml, p2-feature/org.eclipse.collections.repository/pom.xml, pom.xml
=> Add OSGi metadata and correct repository build

p2-feature/org.eclipse.collections.feature/feature.xml, p2-feature/org.eclipse.collections.feature/pom.xml, p2-feature/org.eclipse.collections.repository/pom.xml, p2-feature/pom.xml
=> Correct versions in p2-feature and repository

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java
=> Simplify implementation of containsBy on RichIterable.

site/cn/index.html, site/de/index.html, site/el/index.html, site/es/index.html, site/fr/index.html, site/hi/index.html, site/index.html, site/ja/index.html, site/pt-br/index.html, site/ru/index.html
Fix #954.  I changed gradle dependency setting in website.
=> Fix gradle dependency settings in website

p2-feature/pom.xml, p2-repository/pom.xml
This is to try and fix the JDK 15 Build.
=> Upgrade tycho plugin from 1.2.0 to 1.7.0

eclipse-collections-api/src/main/java/org/eclipse/collections/api/tuple/package-info.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/tuple/Tuples.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/tuple/package-info.java, unit-tests/src/test/java/org/eclipse/collections/impl/tuple/TuplesTest.java
Also fixed package-info for Tuples
=> Add Tuples.identicalTwin() and Tuples.identicalTriplet()

README.md
Signed-off-by: bmvermeer <brianvermeer@snyk.io>
=> security badge in README.md

.github/workflows/coverage.yaml, pom.xml
Signed-off-by: GracianoR <rodrigo.graciano@bnymellon.com>
=> Add GitHub action to generate code report #968

.github/workflows/earlyaccess-javadoc.yml, .github/workflows/earlyaccess-unit.yml, eclipse-collections/src/main/java/org/eclipse/collections/impl/string/immutable/CharAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/string/immutable/CodePointAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/string/immutable/CodePointList.java, p2-repository/pom.xml
There will be failures in EBR Maven plugin. But that needs to be fixed in EBR Maven plugin. That said, the main library will be tested correctly.
=> Create JDK-EA builds and fix Compiler errors due to new default method in JDK-15

unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/primitive/AbstractObjectBooleanMapTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/primitive/ObjectBooleanHashMapTestCase.java
=> Fixed missing test coverage for ObjectBooleanHashMapWithHashingStrategy.

site/cn/index.html, site/de/index.html, site/el/index.html, site/es/index.html, site/fr/index.html, site/hi/index.html, site/index.html, site/ja/index.html, site/pt-br/index.html, site/ru/index.html
This integrates the security badge on the homepage (all languages)
This will automatically update to the latest release version on maven central.
Signed-off-by: bmvermeer <brianvermeer@snyk.io>
=> integrating security badge on homepage.

eclipse-collections/src/main/java/org/eclipse/collections/impl/lazy/CollectIterable.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/CollectIterableTest.java
=> Fix CollectIterable detect methods. Closes #994

docs/jackson.md
This is an old draft blog article of mine. The 'Eclipse Collections' section should probably be removed, explaining that is the job of other docs. Feedback appreciated!
=> Documentation on serializing EC with jackson

README.md, docs/jackson.md
=> Add jackson.md to README.md.

site/cn/index.html, site/de/index.html, site/el/index.html, site/es/index.html, site/fr/index.html, site/hi/index.html, site/index.html, site/ja/index.html, site/pt-br/index.html, site/ru/index.html
Signed-off-by: bmvermeer <brianvermeer@snyk.io>
Solving issue #986
=> adding relevant badges to website

eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/AbstractImmutableBagIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/AbstractMutableBagIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/UnmodifiableBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/UnmodifiableSortedBag.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/RichIterableTestCase.java
=> Optimize sumBy Primitive methods for Bags. Closes #448.

eclipse-collections-code-generator/src/main/resources/impl/set/mutable/primitiveHashSet.stg
Signed-off-by: Mohammad Rezaei <mohdev@rezaei.cc>
=> Optimize toImmutable on primitive sets

eclipse-collections-code-generator/src/main/resources/api/set/immutablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/api/set/mutablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/api/set/primitiveSet.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractImmutablePrimitiveSetTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractPrimitiveSetTestCase.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/primitive/BooleanHashSet.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractBooleanSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractByteSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractImmutableByteHashSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/ImmutableBooleanHashSetTest.java
=> Implement intersect operation on primitive sets. Partially addresses issues #310. 

pom-template, pom.xml
@prathasirisha Please review this and if looks good do the honors of merging it. It will test your commit rights as well.
=> Update developer details

README.md
Signed-off-by: Aditi Mantri <aditi.mantri@bnymellon.com>
=> Create EC and JDK compatibility table in README. Partially closes #985.

README.md
=> Update version numbers and add links to 10.x release notes in README.md compatibility matrix.

eclipse-collections-code-generator/src/main/resources/api/set/immutablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/api/set/mutablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/api/set/primitiveSet.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractImmutablePrimitiveSetTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractPrimitiveSetTestCase.stg, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractBooleanSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractByteSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractImmutableByteHashSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/ImmutableBooleanHashSetTest.java
=> Implement difference operation on primitive sets. Partially closes #310.

eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/SetIterables.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/internal/SetIterablesTest.java
=> Port optimizations for primitive set operations to SetIterables.

eclipse-collections-code-generator/src/main/resources/api/set/immutablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/api/set/mutablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/api/set/primitiveSet.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractImmutablePrimitiveSetTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractPrimitiveSetTestCase.stg, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractBooleanSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractByteSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractImmutableByteHashSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/ImmutableBooleanHashSetTest.java
=> Implement symmetric difference on primitive sets. Partially addresses #310.

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/Interval.java
Signed-off-by: Vibhuti Singh <vibhutisingh037@gmail.com>
=> Issue #775

eclipse-collections-code-generator/src/main/resources/api/set/primitiveSet.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractImmutablePrimitiveSetTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractPrimitiveSetTestCase.stg, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractBooleanSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractByteSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractImmutableByteHashSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/ImmutableBooleanHashSetTest.java
=> Implement isSubsetOf operation on primitive sets. Partially addresses #310.

eclipse-collections-code-generator/src/main/resources/api/set/primitiveSet.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractImmutablePrimitiveSetTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractPrimitiveSetTestCase.stg, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractBooleanSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractByteSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractImmutableByteHashSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/ImmutableBooleanHashSetTest.java
=> Implement isProperSubsetOf operation on primitive sets. Partially addresses #310.

unit-tests/src/test/java/org/eclipse/collections/impl/utility/internal/SetIterablesTest.java
=> Remove failing test unionPerformance

eclipse-collections-code-generator/src/main/resources/api/set/primitiveSet.stg, eclipse-collections-code-generator/src/main/resources/impl/map/abstractMutablePrimitiveKeySet.stg, eclipse-collections-code-generator/src/main/resources/impl/set/abstractPrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/impl/set/immutable/immutablePrimitiveEmptySet.stg, eclipse-collections-code-generator/src/main/resources/impl/set/immutable/immutablePrimitiveSingletonSet.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/synchronizedPrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/unmodifiablePrimitiveSet.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractImmutablePrimitiveSetTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/set/mutable/abstractPrimitiveSetTestCase.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/immutable/primitive/ImmutableBooleanEmptySet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/immutable/primitive/ImmutableFalseSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/immutable/primitive/ImmutableTrueFalseSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/immutable/primitive/ImmutableTrueSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/primitive/BooleanHashSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/primitive/ByteHashSet.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/immutable/primitive/ImmutableBooleanEmptySetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractBooleanSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractByteSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractImmutableByteHashSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/ImmutableBooleanHashSetTest.java
=> Implement cartesianProduct operation on primitive sets. Closes #310.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/ImmutableBag.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/MutableBag.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/ImmutableList.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/list/MutableList.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/set/ImmutableSet.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/set/MutableSet.java, unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java
=> Add toImmutableList/Set/Bag to RichIterable interface.

eclipse-collections-code-generator/src/main/resources/impl/bag/immutable/immutablePrimitiveSingletonBag.stg, eclipse-collections-code-generator/src/main/resources/impl/iterator/singletonPrimitiveIterator.stg, eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveSingletonList.stg, eclipse-collections-code-generator/src/main/resources/impl/set/immutable/immutablePrimitiveSingletonSet.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/immutable/immutablePrimitiveSingletonStack.stg
Optimize the creation of iterators for singleton primitive collections.
=> Add primitive singleton iterator

acceptance-tests/src/test/java/org/eclipse/collections/impl/map/mutable/UnifiedMapAcceptanceTest.java, acceptance-tests/src/test/java/org/eclipse/collections/impl/set/mutable/UnifiedSetAcceptanceTest.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMapUnsafe.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/string/immutable/CodePointAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/string/immutable/CodePointList.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/sorted/mutable/AbstractMutableSortedBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/AbstractListTestCase.java
The enhanced for-loop syntax helps eliminate unnecessary boilerplate during iteration.
=> Use enhanced for-loop syntax wherever as possible

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java, unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java
=> Add toImmutableMap to RichIterable.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java, unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java
=> Add toImmutableBiMap to RichIterable.

README.md
=> Update README.md JDK Compatability Matrix.

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java
=> Add toSortedMap and toSortedMapBy to Collectors2. Closes #1046.

unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/AdaptObjectIntProcedureToProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/BagAddOccurrencesProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/CaseProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/ChainedProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/CollectProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/CollectionAddProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/CollectionRemoveProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/CounterProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/IfProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/MaxByProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/MaxProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/MinByProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/MinComparatorProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/MinProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/RejectProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/SelectInstancesOfProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/SelectProcedureTest.java
Signed-off-by: Alexander Goldberg <alexander.goldberg@bnymellon.com>
=> #1109 Improve Pit Coverage

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java
I also fixed two javadoc statements around toSortedMap and toSortedMayBy from my previous commit.
=> Add toImmutableSortedMap and toImmutableSortedMapBy to Collectors2

unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java
Improving code readability - Extracting actual and expected variables, so the types are visible in the tests.
=> Refactor Collectors2Test to extract actual and expected variables

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java
Signed-off-by: Utkarsh Nagar <utkarshnagar2000@gmail.com>
=> Add toImmutableSortedBagBy to Collectors2

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java
Signed-off-by: Utkarsh Nagar <utkarshnagar2000@gmail.com>
=> Add toImmutableSortedListBy to Collectors2. Closes #1136

.github/workflows/earlyaccess-javadoc.yml, .github/workflows/earlyaccess-unit.yml, .github/workflows/javadoc.yml, .github/workflows/unit-no-p2.yml, .github/workflows/unit.yml
=> Add JDK 17 to standard builds and update EA builds to JDK 18.

unit-tests/src/test/java/org/eclipse/collections/api/factory/bag/MutableBagFactoryTest.java, unit-tests/src/test/java/org/eclipse/collections/api/factory/stack/MutableStackFactoryTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/EmptyIteratorTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableBagFactoryTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/ListsTest.java
Signed-off-by: Alexander Goldberg <alexander.goldberg@bnymellon.com>
=> #1109: Improve Pit Coverage

README.md
=> Add Java 17 to README.MD.

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java
Signed-off-by: Ly (Harriet) Bui <lhbui@umass.edu>
=> Add toImmutableSortedSetBy to Collectors2. Resolved #1137

.github/workflows/coverage.yaml, .github/workflows/mutation.yml
=> Upgrade coverage, mutation GitHub actions to Java 11.

eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/ClassComparer.java, eclipse-collections-testutils/src/test/java/org/eclipse/collections/impl/test/ClassComparerTest.java
=> Add ClassComparer to test-utils.

pom.xml
=> Upgrade build and test library dependencies.

README.md, README_EXAMPLES.md, RELEASE_NOTE_DRAFT.md, site/cn/index.html, site/de/index.html, site/el/index.html, site/es/index.html, site/fr/index.html, site/hi/index.html, site/index.html, site/ja/index.html, site/no-nb/index.html, site/pt-br/index.html, site/ru/index.html
=> Eclipse Collections 11.0 release prep 

eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/ClassComparer.java, eclipse-collections-testutils/src/test/java/org/eclipse/collections/impl/test/ClassComparerTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/FastListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/UnifiedMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/UnifiedSetTest.java
=> Add superset tests for FastList, UnifiedMap and UnifiedSet.

docs/guide.md
=> Update guide.md with minor cleanup and javadoc link updates.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/ServiceLoaderUtils.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/primitive/package-info.java, eclipse-collections-code-generator-maven-plugin/src/main/java/org/eclipse/collections/codegenerator/maven/GenerateMojo.java, eclipse-collections-code-generator/src/main/java/org/eclipse/collections/codegenerator/EclipseCollectionsCodeGenerator.java, eclipse-collections-code-generator/src/main/resources/api/factory/primitiveListsAPI.stg, eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveListFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/mutablePrimitiveListFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/impl/services/serviceImmutablePrimitiveListFactory.stg, eclipse-collections-code-generator/src/main/resources/impl/services/serviceMutablePrimitiveListFactory.stg, eclipse-collections-code-generator/src/main/resources/test/factory/primitiveListsTest.stg, eclipse-collections/pom.xml
=> Generate primitive List factories in API using ServiceLoader.

README.md
=> Update README.md with OSS projects that use Eclipse Collections.

unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/SumOfDoubleProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/SumOfFloatProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/SumOfIntProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/SumOfLongProcedureTest.java
=> Add SumOfLong/Int/Double/FloatProcedure tests. Partially addresses #991.

eclipse-collections-code-generator/src/main/resources/test/block/procedure/sumOfPrimitiveProcedureTest.stg
Add test for SumOfShortProcedure.
Related issue: #991
=> Add test for SumOfPrimitiveProcedure

eclipse-collections-code-generator/src/main/resources/api/list/immutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/list/mutablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/list/primitiveList.stg, eclipse-collections-code-generator/src/main/resources/api/ordered/orderedPrimitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/api/ordered/reversiblePrimitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/api/stack/immutablePrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/api/stack/mutablePrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/api/stack/primitiveStack.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/synchronizedPrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/unmodifiablePrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/immutable/immutablePrimitiveArrayStack.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/mutable/synchronizedPrimitiveStack.stg, eclipse-collections-code-generator/src/main/resources/test/list/immutable/abstractImmutablePrimitiveListTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/abstractPrimitiveListTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/stack/mutable/abstractPrimitiveStackTestCase.stg, unit-tests/src/test/java/org/eclipse/collections/impl/WordleTest.java
=> Add selectWithIndex and rejectWithIndex to Ordered primitive Iterables.

eclipse-collections-code-generator/src/main/resources/api/primitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/test/collection/mutable/abstractPrimitiveIterableTestCase.stg
=> Primitive inject into

eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/set/primitive/package-info.java, eclipse-collections-code-generator/src/main/resources/api/factory/primitiveSetsAPI.stg, eclipse-collections-code-generator/src/main/resources/impl/set/immutable/immutablePrimitiveSetFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/mutablePrimitiveSetFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/services/serviceImmutablePrimitiveSetFactory.stg, eclipse-collections-code-generator/src/main/resources/services/serviceMutablePrimitiveSetFactory.stg, eclipse-collections-code-generator/src/main/resources/test/factory/primitiveSetsTest.stg
Signed-off-by: Rinat Gatyatullin <rinattalgatovich.gatyatullin@bnymellon.com>
=> Add primitive Set factories in API. Closes #1205.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/stack/primitive/package-info.java, eclipse-collections-code-generator/src/main/resources/api/factory/primitiveStacksAPI.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/immutable/immutablePrimitiveStackFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/impl/stack/mutable/mutablePrimitiveStackFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/services/serviceImmutablePrimitiveStackFactory.stg, eclipse-collections-code-generator/src/main/resources/services/serviceMutablePrimitiveStackFactory.stg, eclipse-collections-code-generator/src/main/resources/test/factory/primitiveStacksTest.stg
Signed-off-by: Rinat Gatyatullin <rinattalgatovich.gatyatullin@bnymellon.com>
=> Add primitive Stack factories in API. Closes #1207.

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/immutable/AbstractImmutableList.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/ArrayListAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/RandomAccessListAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/immutable/AbstractImmutableSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/AbstractMutableSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/SetAdapter.java
=> Remove dependencies on primitive collection implementations.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/Lists.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/MultiReaderMutableListFactory.java, eclipse-collections/src/main/resources/META-INF/services/org.eclipse.collections.api.factory.list.MultiReaderListFactory, unit-tests/src/test/java/org/eclipse/collections/impl/factory/ListsTest.java
Signed-off-by: Aqsa Malik <aqsa.malik@bnymellon.com>
=> Add MultiReader to Lists factory in API module. Closes #1202.

eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/AbstractImmutableBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableEmptyBag.java
Signed-off-by: John Stuart <john.stuart@bnymellon.com>
=> Remove dependencies on primitive collection implementations

eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/Bags.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderMutableBagFactory.java, eclipse-collections/src/main/resources/META-INF/services/org.eclipse.collections.api.factory.bag.MultiReaderBagFactory, unit-tests/src/test/java/org/eclipse/collections/impl/factory/BagsTest.java
Signed-off-by: Aqsa Malik <aqsa.malik@bnymellon.com>
=> Add multiReader to Bags factory in API module. Closes #1237.

eclipse-collections-code-generator/src/main/resources/api/factory/primitiveObjectMapsAPI.stg, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutablePrimitiveObjectMapFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/mutablePrimitiveObjectMapFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/services/serviceImmutablePrimitiveObjectMapFactory.stg, eclipse-collections-code-generator/src/main/resources/services/serviceMutablePrimitiveObjectMapFactory.stg, eclipse-collections-code-generator/src/main/resources/test/factory/primitiveObjectMapsTest.stg
@donraab happy to hear any feedback - thanks
=> Migrate primitive -> object maps to service loader

eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/HashBag.java
=> Remove the direct dependency on ObjectIntHashMap in HashBag.

eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/AbstractImmutableBagIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/AbstractMutableBagIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/UnmodifiableBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/UnmodifiableSortedBag.java
Signed-off-by: John Stuart <john.stuart@bnymellon.com>
=> Remove dependencies on object -> primitive map implementations in bags

eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MapIterable.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/MapIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/MapIterableTestCase.java
Signed-off-by: Emilie Robichaud <emilie.robichaud@bnymellon.com>
=> Add injectIntoKeyValue to MapIterable. Closes #1244.

eclipse-collections/src/main/java/org/eclipse/collections/impl/collector/Collectors2.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/parallel/ParallelIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/IterableIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/RandomAccessListIterate.java
=> Remove primitive map dependencies from static utility classes.

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/IntInterval.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/LongInterval.java
=> Remove IntPredicates and LongPredicates as dependendencies.

eclipse-collections-code-generator/src/main/resources/copyright.stg, eclipse-collections-code-generator/src/main/resources/copyrightAndOthers.stg, eclipse-collections-code-generator/src/main/resources/copyrightOf.stg
=> Add parameterized copyright template and update copyright templates.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/bag/Bag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableArrayBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableEmptyBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableSingletonBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/AbstractHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/SynchronizedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/UnmodifiableBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/immutable/ImmutableEmptySortedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/immutable/ImmutableSortedBagImpl.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/SynchronizedSortedBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/TreeBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/sorted/mutable/UnmodifiableSortedBag.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableArrayBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBagAsReadUntouchableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBagAsWriteUntouchableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MutableBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/SynchronizedBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/UnmodifiableBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/sorted/immutable/AbstractImmutableSortedBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/sorted/immutable/ImmutableSortedBagImplTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/sorted/mutable/AbstractMutableSortedBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/sorted/mutable/SynchronizedSortedBagTest.java
A simple implementation for #726 after the failed attempts of #797, #861 and #869 :)
=> Add Bag.distinctView() for #726

eclipse-collections-code-generator/src/main/resources/api/factory/objectPrimitiveMapsAPI.stg, eclipse-collections-code-generator/src/main/resources/impl/factory/objectPrimitiveMaps.stg, eclipse-collections-code-generator/src/main/resources/impl/factory/primitiveBags.stg, eclipse-collections-code-generator/src/main/resources/impl/factory/primitiveLists.stg, eclipse-collections-code-generator/src/main/resources/impl/factory/primitiveObjectMaps.stg, eclipse-collections-code-generator/src/main/resources/impl/factory/primitivePrimitiveMaps.stg, eclipse-collections-code-generator/src/main/resources/impl/factory/primitiveSets.stg, eclipse-collections-code-generator/src/main/resources/impl/factory/primitiveStacks.stg
=> Fix incorrect Javadoc in stg files

eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableArrayStack.java
=> Remove impl stack dependencies in ImmutableArrayStack

eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitivePrimitiveHashMap.stg
=> Replace impl with api factories in primitive map templates.

eclipse-collections-code-generator/src/main/resources/api/factory/map/mutableObjectPrimitiveHashingStrategyMapFactory.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/mutableObjectPrimitiveHashingStrategyMapFactoryImpl.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMapWithHashingStrategy.stg, eclipse-collections-code-generator/src/main/resources/test/factory/objectPrimitiveHashingStrategyMapsTest.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/strategy/mutable/HashBagWithHashingStrategy.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/primitive/ObjectBooleanHashMapWithHashingStrategy.java
=> Add withInitialCapacity api in mutableObjectPrimitiveHashingStrategyMapFactory

eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMapWithHashingStrategy.stg
Signed-off-by: Chandra Guntur <chandra.guntur@bnymellon.com>
=> Replace impl with api factories in objectPrimitiveHashMapWithHashingStrategy.stg

eclipse-collections-code-generator/src/main/resources/impl/map/mutable/objectPrimitiveHashMapWithHashingStrategy.stg
Signed-off-by: Chandra Guntur <chandra.guntur@bnymellon.com>
=> Remove primitive ArrayList, HashBag/Set from objectPrimitiveHashMapWithHashingStrategy.stg

eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/AbstractSynchronizedRichIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/immutable/AbstractImmutableSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/immutable/ImmutableUnifiedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/MultiReaderUnifiedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/SetAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/mutable/UnmodifiableMutableSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/sorted/immutable/AbstractImmutableSortedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/sorted/mutable/SortedSetAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/sorted/mutable/TreeSortedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/sorted/mutable/UnmodifiableSortedSet.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/set/strategy/immutable/ImmutableUnifiedSetWithHashingStrategy.java, scala-unit-tests/src/test/scala/org/eclipse/collections/impl/set/mutable/MultiReaderUnifiedSetScalaTest.scala
Hi,
Here are a few commits that were laying around as left overs of my abandoned work on #797 and #869 :)
=> A few improvements on Set implementations

.github/workflows/acceptance.yml, .github/workflows/checkstyle.yml, .github/workflows/coverage.yaml, .github/workflows/findbugs.yml, .github/workflows/javadoc.yml, .github/workflows/mutation.yml, .github/workflows/performance.yml, .github/workflows/unit-no-p2.yml, .github/workflows/unit.yml
https://github.com/actions/setup-java/blob/main/README.md
=> setup-java v3

eclipse-collections-forkjoin/src/main/java/org/eclipse/collections/impl/forkjoin/FJIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/parallel/ParallelIterate.java
=> Update ParallelIterate and FJIterate JavaDoc to use lambdas.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/MutableMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/bag/MutableBagIterableMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/bag/MutableBagMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/list/MutableListMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/set/MutableSetIterableMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/set/MutableSetMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/sortedbag/MutableSortedBagMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/sortedset/MutableSortedSetMultimap.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/bag/HashBagMultimapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/bag/SynchronizedBagMultimapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/bag/sorted/TreeBagMultimapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/bag/sorted/mutable/SynchronizedSortedBagMultimapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/bag/sorted/mutable/TreeBagMultimapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/bag/strategy/HashBagMultimapWithHashingStrategyTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/list/FastListMultimapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/list/SynchronizedListMultimapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/set/SynchronizedSetMultimapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/set/UnifiedSetMultimapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/set/sorted/SynchronizedPutTreeSortedSetMultimapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/set/sorted/SynchronizedSortedSetMultimapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/set/sorted/TreeSortedSetMultimapTest.java
=> Add withKeyValue to MutableMultimap and subtypes. Closes #1303.

.idea/inspectionProfiles/IDE.xml, eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/bag/MutableBagFactory.java, eclipse-collections-code-generator/src/main/resources/impl/map/abstractMutablePrimitiveValuesMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/AbstractBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/HashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/mutable/MutableBagFactoryImpl.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/Interval.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/primitive/AbstractMutableBooleanValuesMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/bag/SynchronizedPutHashBagMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/parallel/AbstractTransformerBasedCombiner.java, unit-tests/src/test/java/org/eclipse/collections/impl/factory/BagsTest.java
=> Implement Bags.mutable.withInitialCapacity. Closes #1318

eclipse-collections-code-generator/src/main/resources/api/block/function/objectObjectPrimitiveToObjectFunction.stg, eclipse-collections-code-generator/src/main/resources/api/map/objectPrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/primitiveObjectMap.stg, eclipse-collections-code-generator/src/main/resources/api/map/primitivePrimitiveMap.stg, eclipse-collections-code-generator/src/main/resources/test/map/abstractObjectPrimitiveMapTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/map/abstractPrimitivePrimitiveMapTestCase.stg
Signed-off-by: Emilie Robichaud <emilie.robichaud@bnymellon.com>
=> Add injectIntoKeyValue to objectPrimitiveMap. Closes #1217.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/MutableMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/bag/MutableBagIterableMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/bag/MutableBagMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/list/MutableListMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/set/MutableSetIterableMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/set/MutableSetMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/sortedbag/MutableSortedBagMultimap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/multimap/sortedset/MutableSortedSetMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/AbstractSynchronizedMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/AbstractSynchronizedPutMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/bag/SynchronizedBagMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/bag/SynchronizedPutHashBagMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/bag/sorted/mutable/SynchronizedSortedBagMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/list/SynchronizedListMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/list/SynchronizedPutFastListMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/set/SynchronizedPutUnifiedSetMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/set/SynchronizedSetMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/set/sorted/SynchronizedPutTreeSortedSetMultimap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/multimap/set/sorted/SynchronizedSortedSetMultimap.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/AbstractMutableMultimapTestCase.java
Signed-off-by: Alexander Goldberg <alexander.goldberg@bnymellon.com>
=> Add withKeyMultiValues to MutableMultimap and subtypes. Closes #1307.

eclipse-collections-code-generator/src/main/resources/impl/bag/mutable/primitiveHashBag.stg, eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutablePrimitiveObjectEmptyMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutablePrimitiveObjectSingletonMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg
=> Remove dependency on FastList in primitive collections.

eclipse-collections-api/src/main/java/org/eclipse/collections/api/RichIterable.java, unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java
=> Optimize containsAny and containsNone on RichIterable.

eclipse-collections/src/main/java/org/eclipse/collections/impl/map/AbstractMapIterable.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/RichIterableTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/mutable/UnifiedMapWithHashingStrategyNoIteratorTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/MapIterableTestCase.java
=> Add tests for containsAny/containsNone to RichIterableTestCase

eclipse-collections-api/src/main/java/org/eclipse/collections/api/stack/ImmutableStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableArrayStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableEmptyStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableNotEmptyStack.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/stack/immutable/ImmutableStackTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/stack/immutable/ImmutableArrayStackTest.java
Closes #1048
Signed-off-by: Roberto Falzarano <robertofalzarano@gmail.com>
=> change signature of pops methods in ImmutableStack

eclipse-collections-code-generator/src/main/resources/api/primitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/impl/lazy/collectPrimitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/impl/lazy/selectPrimitiveIterable.stg, eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/map/abstractMutablePrimitiveKeySet.stg, eclipse-collections-code-generator/src/main/resources/impl/map/abstractMutablePrimitiveValuesMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveBooleanHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/set/mutable/primitiveHashSet.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/IntInterval.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/LongInterval.java
=> Make noneSatisfy a default method on primitiveIterable.stg.

eclipse-collections-code-generator/src/main/resources/api/list/primitiveList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/synchronizedPrimitiveList.stg, eclipse-collections-code-generator/src/main/resources/test/list/mutable/abstractPrimitiveListTestCase.stg, unit-tests/src/test/java/org/eclipse/collections/impl/WordleTest.java
=> Implement forEachInBoth on primitive Lists.

README.md, docs/1-Iteration_Patterns.adoc, docs/3-Code_Blocks.adoc, docs/guide.md
=> Add links to Javadoc; update links to new Ref Guide

docs/2-Collection_Containers.adoc
=> Fix some issues in collection containers section of reference guide.

docs/1-Iteration_Patterns.adoc
=> Add linenums to Iteration Patterns asciidoc

eclipse-collections-api/src/main/java/org/eclipse/collections/api/factory/ServiceLoaderUtils.java
This is an experimental patch. Don't merge immediately.
=> Reflection fallback for serviceloader

README.md, README_EXAMPLES.md, RELEASE_NOTE_DRAFT.md, docs/1-Iteration_Patterns.adoc, docs/2-Collection_Containers.adoc, docs/3-Code_Blocks.adoc, docs/4-Testing_Utilities.adoc, docs/5-Quick_Reference.adoc, docs/guide.md, site/cn/index.html, site/de/index.html, site/el/index.html, site/es/index.html, site/fr/index.html, site/hi/index.html, site/index.html, site/ja/index.html, site/no-nb/index.html, site/pt-br/index.html, site/ru/index.html
=> Eclipse Collections 11.1 release prep

eclipse-collections-code-generator/src/main/resources/impl/list/immutable/immutablePrimitiveArrayList.stg, eclipse-collections-code-generator/src/main/resources/impl/list/mutable/primitiveArrayList.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/string/immutable/CharAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/string/immutable/CodePointAdapter.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/InternalArrayIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/IteratorIterate.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/internal/RandomAccessListIterate.java
=> Refactor distinct to use select.

docs/2-Collection_Containers.adoc
updated typo in Primitive Lists Example:38 from creCreate to Create.
Line No: 940.
=> updated typo in Primitive Lists

docs/2-Collection_Containers.adoc
Provide example for creation with different set of available methods. 
Examples provided for different set of operations available in primitive sets.
This pull request is against open [issue](https://github.com/eclipse/eclipse-collections/issues/1385)
#1385
=> Updated #1385, 2-Collection_Containers.adoc file updated for Primitive sets

docs/2-Collection_Containers.adoc
#1384 
Added examples for IntInterval class with different set of examples.
=> 2-Collection_Containers.adoc file updated for IntInterval Document

eclipse-collections-code-generator/src/main/resources/api/map/mutablePrimitiveObjectMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/primitiveObjectHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/synchronizedPrimitiveObjectMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/unmodifiablePrimitiveObjectMap.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/abstractMutablePrimitiveObjectMapTestCase.stg, eclipse-collections-code-generator/src/main/resources/test/map/mutable/unmodifiablePrimitiveObjectMapTest.stg, pom.xml
See #1418. This is just for primitiveObject maps. Implementations for objectPrimitive and primitivePrimitive are still needed.
=> add removeIf to primitiveObject maps

eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/ConcurrentMutableMap.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MapIterable.java, eclipse-collections-api/src/main/java/org/eclipse/collections/api/map/MutableMapIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/immutable/AbstractImmutableBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/immutable/AbstractImmutableMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/immutable/AbstractImmutableSortedMap.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/bimap/BiMapTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/MapIterableTestCase.java
Signed-off-by: Robin Zheng <robin.zheng@bnymellon.com>
=> Override Java 8 default method Map#forEach - closes #1423

.github/workflows/earlyaccess-javadoc.yml, .github/workflows/earlyaccess-unit.yml, eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/ClassComparer.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/UnifiedMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/UnifiedSetTest.java
Signed-off-by: Aqsa Malik [aqsa.malik@bnymellon.com](mailto:aqsa.malik@bnymellon.com)
=> Update EA versions to 19, 20, 21

eclipse-collections/src/main/java/org/eclipse/collections/impl/list/mutable/primitive/BooleanArrayList.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/primitive/BooleanArrayListTest.java
Signed-off-by: Alexander Goldberg <alexander.goldberg@bnymellon.com>
=> Fixed a bug in addAllAtIndex method. Closes #1433.

docs/2-Collection_Containers.adoc
Improves Readability.
helps #1443
=> [doc] Removed white space from the document (primitive-maps example)

.github/workflows/acceptance.yml, .github/workflows/javadoc.yml, .github/workflows/performance.yml, .github/workflows/unit.yml, .idea/compiler.xml, .idea/eclipse-collections-parent.iml, acceptance-tests/acceptance-tests.iml, eclipse-collections-api/eclipse-collections-api.iml, eclipse-collections-api/pom.xml, eclipse-collections-code-generator-maven-plugin/eclipse-collections-code-generator-maven-plugin.iml, eclipse-collections-code-generator-maven-plugin/pom.xml, eclipse-collections-code-generator/eclipse-collections-code-generator.iml, eclipse-collections-code-generator/pom.xml, eclipse-collections-forkjoin/eclipse-collections-forkjoin.iml, eclipse-collections-parent.iml, eclipse-collections-testutils/eclipse-collections-testutils.iml, eclipse-collections-testutils/pom.xml, eclipse-collections/eclipse-collections.iml, eclipse-collections/pom.xml, junit-trait-runner/junit-trait-runner.iml, missing-dependency/missing-dependency.iml, p2-repository/org.eclipse.collections/org.eclipse.collections.iml, p2-repository/p2-repository.iml, performance-tests/performance-tests.iml, pom.xml, scala-unit-tests/scala-unit-tests.iml, serialization-tests/serialization-tests.iml, unit-tests-java8/unit-tests-java8.iml, unit-tests/unit-tests.iml
Previous conversation here - https://github.com/eclipse/eclipse-collections/pull/1479 
@nikhilnanivadekar  to your comment [here](https://github.com/eclipse/eclipse-collections/pull/1479#issuecomment-1661284819) - I have not heard back on the ticket I created for Javadoc issue. I spot-checked a few classes and they look good. At this point, it makes sense to merge this PR and move forward if others are okay with it too. 
Apologies for creating a new PR as I am unable to re-open the previous one.
=> Java 11 upgrade

eclipse-collections-code-generator/src/main/resources/impl/map/immutable/immutablePrimitiveObjectHashMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/synchronizedPrimitiveObjectMap.stg, eclipse-collections-code-generator/src/main/resources/impl/map/mutable/unmodifiablePrimitiveObjectMap.stg, eclipse-collections/src/main/java/org/eclipse/collections/impl/UnmodifiableRichIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bag/immutable/ImmutableHashBag.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/AbstractBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/mutable/UnmodifiableBiMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/block/factory/StringPredicates.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/AbstractSynchronizedRichIterable.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/mutable/AbstractMultiReaderMutableCollection.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/collection/mutable/AbstractUnmodifiableMutableCollection.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/mutable/UnmodifiableMutableMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/ordered/mutable/UnmodifiableMutableOrderedMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/map/sorted/mutable/UnmodifiableTreeMap.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/SynchronizedStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/UnmodifiableStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/Iterate.java
* main code, tests are not affected
* only methods with a documented replacement
There is no functional change, as long as all deprecation replacements have been documented and delegated correctly before.
=> Forward deprecated methods to their new replacement

eclipse-collections-code-generator/src/main/resources/test/map/mutable/primitiveBooleanHashMapKeySetTest.stg
Relates to #1579 which still had one extra test override left.
=> Replace usages of @Test(expected) with Assert.assertThrows().

checkstyle-configuration.xml
Our Checkstyle configuration borrows a lot of ideas from the configuration that the Checkstyle project runs on its own code.
https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle-checks.xml
They've cleaned up some configuration and turned on more rules that pass on our project, so this PR resyncs our configuration with "upstream"
=> Sync Checkstyle configuration with upstream examples.

acceptance-tests/pom.xml, checkstyle-configuration.xml, eclipse-collections-forkjoin/pom.xml, eclipse-collections-testutils/pom.xml, performance-tests/pom.xml, pom.xml, serialization-tests/pom.xml, unit-tests-java8/pom.xml, unit-tests/pom.xml
@Desislav-Petrov another small step on the way to JUnit 5.
=> Add dependency on junit-jupiter-api.

unit-tests/src/test/java/org/eclipse/collections/impl/bag/sorted/mutable/UnmodifiableSortedBagTest.java
=> Uplift Junit syntax for UnmodifiableSortedBagTest

unit-tests/src/test/java/org/eclipse/collections/impl/AbstractRichIterableTestCase.java
=> Remove expected from AbstractRichIterableTestCase

unit-tests/src/test/java/org/eclipse/collections/impl/UnmodifiableMapEntrySetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/UnmodifiableRichIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/fixed/EmptyMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/sorted/mutable/SortedMapAdapterTest.java
=> Remove expected from 4 tests

unit-tests/src/test/java/org/eclipse/collections/impl/UnmodifiableMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBagAsUnmodifiableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/primitive/UnmodifiableBooleanBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collection/mutable/CollectionAdapterTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collection/mutable/UnmodifiableMutableCollectionTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collection/mutable/UnmodifiableMutableCollectionTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/collection/mutable/primitive/AbstractBooleanIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/collection/mutable/primitive/AbstractMutableBooleanStackTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/iterator/ZipIteratorTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/parallel/list/UnmodifiableMutableListParallelListIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/parallel/set/UnmodifiableUnsortedSetParallelTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastListAsUnmodifiableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/UnmodifiableMutableListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/primitive/UnmodifiableBooleanListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/primitive/UnmodifiableObjectBooleanMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/MultiReaderUnifiedSetAsUnmodifiableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/UnmodifiableMutableSetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/UnmodifiableBooleanSetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/stack/mutable/UnmodifiableStackTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/stack/mutable/primitive/UnmodifiableBooleanStackTest.java
@motlin Finally got a semi automated script to help with the migration through chatgpt. Will chunk in multiple PRs for easier review 
cc @donraab
=> Remove more expected from tests

unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/AtomicCountProcedureTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/collector/Collectors2Test.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/DistinctIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/DropIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/iterator/CollectIteratorTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/iterator/DistinctIteratorTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/primitive/CollectBooleanToObjectIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/fixed/ArrayAdapterTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/CompositeFastListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/primitive/BooleanArrayListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/primitive/BoxedMutableBooleanListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/ConcurrentHashMapUnsafeTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/BoxedMutableBooleanSetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/ByteHashSetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/sorted/mutable/AbstractSortedSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/ArrayIterateTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/ArrayListIterateTest.java
=> Remove expected 7

eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableEmptyStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/immutable/ImmutableNotEmptyStack.java, eclipse-collections/src/main/java/org/eclipse/collections/impl/stack/mutable/ArrayStack.java, unit-tests/src/test/java/org/eclipse/collections/impl/stack/StackIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/stack/mutable/ArrayStackTest.java
=> Implement ArrayStack.distinct() method and related unit tests

unit-tests-java8/src/test/java/org/eclipse/collections/test/OrderedIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MutableBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/sorted/mutable/UnmodifiableSortedBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/parallel/ParallelIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/parallel/bag/ParallelBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/parallel/list/ParallelListIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/parallel/set/ParallelUnsortedSetIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/parallel/set/sorted/ParallelSortedSetIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/ImmutableNonupletonListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/ImmutableOctupletonListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/ImmutableQuadrupletonListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/primitive/AbstractImmutableBooleanListTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/primitive/AbstractBooleanListTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/primitive/ObjectBooleanHashMapKeySetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/primitive/ObjectBooleanHashMapTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/primitive/ObjectBooleanHashMapValuesTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/partition/stack/PartitionArrayStackTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/MultiReaderUnifiedSetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/primitive/AbstractByteSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/stack/mutable/MutableStackTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/stack/primitive/AbstractBooleanStackTestCase.java
=> Remove expected from tests - #9

unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/primitive/AbstractMutableBooleanBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/sorted/immutable/AbstractImmutableSortedBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bimap/mutable/AbstractMutableBiMapEntrySetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bimap/mutable/AbstractMutableBiMapKeySetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bimap/mutable/AbstractMutableBiMapValuesTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/collection/immutable/AbstractImmutableCollectionTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/AbstractLazyIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/SelectInstancesOfIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/iterator/FlatCollectIteratorTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/ImmutableArrayListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/ImmutableEmptyListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/ImmutableSingletonListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/FastListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/fixed/AbstractMemoryEfficientMutableMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/primitive/AbstractObjectBooleanMapKeyValuesViewTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/multimap/AbstractMutableMultimapTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/fixed/AbstractMemoryEfficientMutableSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/fixed/EmptySetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/fixed/SingletonSetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/immutable/AbstractImmutableEmptySetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/immutable/AbstractImmutableUnifiedSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/immutable/ImmutableSingletonSetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/immutable/primitive/AbstractImmutableByteHashSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/AbstractMutableSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/sorted/immutable/AbstractImmutableSortedSetTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/sorted/immutable/ImmutableEmptySortedSetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/stack/immutable/primitive/AbstractImmutableBooleanStackTestCase.java
=> Remove expected from tests

unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBagAsReadUntouchableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/mutable/MultiReaderHashBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/sorted/immutable/ImmutableEmptySortedBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/function/StringFunctionsTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/iterator/TapIteratorTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/parallel/list/ImmutableListParallelListIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/parallel/list/MultiReaderFastListParallelListIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/parallel/list/RandomAccessListAdapterParallelListIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/parallel/set/sorted/ImmutableEmptySortedSetParallelTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/primitive/ReverseBooleanIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/ImmutableTripletonListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastListAsUnmodifiableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/MultiReaderFastListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/immutable/ImmutableEmptyMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/mutable/UnmodifiableMutableMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/sorted/immutable/ImmutableEmptySortedMapTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/map/strategy/immutable/ImmutableEmptyMapWithHashingStrategyTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/MultiReaderMutableCollectionTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/mutable/MultiReaderUnifiedSetAsWriteUntouchableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/sorted/immutable/ImmutableEmptySortedSetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/sorted/mutable/SortedSetAdapterTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/stack/StackIterableTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/utility/internal/RandomAccessListIterateTest.java
=> Remove more expected

unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableEmptyBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/immutable/ImmutableSingletonBagTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/bag/sorted/mutable/AbstractMutableSortedBagTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/CheckedBlocksTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/block/procedure/ProceduresTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/parallel/set/ImmutableUnifiedSetParallelSetIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/lazy/primitive/FlatCollectBooleanToObjectIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/ImmutableDecapletonListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/ImmutableDoubletonListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/primitive/ImmutableBooleanArrayListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/immutable/primitive/ImmutableBooleanEmptyListTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/list/mutable/AbstractListTestCase.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/immutable/primitive/ImmutableBooleanEmptySetTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/set/strategy/immutable/ImmutableUnifiedSetWithHashingStrategyParallelSetIterableTest.java, unit-tests/src/test/java/org/eclipse/collections/impl/stack/immutable/primitive/ImmutableBooleanEmptyStackTest.java
@motlin final one - will start moving imports after
=> Remove expected - final PR

eclipse-collections/src/main/java/org/eclipse/collections/impl/bimap/mutable/AbstractMutableBiMap.java
=> Optimize forEach method on Map views to not delegate to an iterator.

eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/Verify.java, eclipse-collections-testutils/src/test/java/org/eclipse/collections/impl/test/CollectionsEqualTest.java, eclipse-collections-testutils/src/test/java/org/eclipse/collections/impl/test/ExceptionThrownTest.java, eclipse-collections-testutils/src/test/java/org/eclipse/collections/impl/test/VerifyTest.java
If you hide spaces, this looks like a smaller change. 99 additions and 1,413 deletions.
=> Stop throwing mangled exceptions.

.github/workflows/forbid-merge-commits.yml, .github/workflows/pull-request.yml, eclipse-collections-api/pom.xml, pom.xml
Includes fixes to build plugins, some other quality of life improvements in the builds.
=> Prepare for 12.0.0 Release

CONTRIBUTING.md, RELEASE_NOTE_DRAFT.md
While scanning through the contribution guidelines I've spotted 2 links pointing to outdated locations.
=> Fix dead links

unit-tests-java8/src/test/java/org/eclipse/collections/test/map/immutable/ordered/ImmutableOrderedMapTest.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/mutable/ConcurrentHashMapTest.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/mutable/ConcurrentHashMapUnsafeTest.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/mutable/MapTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/mutable/MutableMapIterableTestCase.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/mutable/UnifiedMapNoIteratorTest.java, unit-tests-java8/src/test/java/org/eclipse/collections/test/map/mutable/UnmodifiableMutableMapIterableTestCase.java
I added tests for four more methods. I didn't add Javadoc for the Map methods because the contacts in the JDK already say that the methods are safe from mutation in the face of exceptions.
=> Add exception safety tests.

README.md
Badge is not version-pinned anymore.
=> Update Snyk badge in README.md
